/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: math-rpc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _MATH_RPC_H_
#define _MATH_RPC_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef math__ns
#define math__ns 167549140
#define math__ns_id "http://example.com/math"
#define math__ns_uri "http://example.com/math"
#endif

#define math_result 401396173
#define math_op 24423668
#define math_math3 630850925
#define math_operand 588456312
#define math_sub 2032895139
#define math_math2 750156742
#define math_add 448306044
#define math_math 446880983
#define math__actionpointid_math3 "math3"

#ifdef __cplusplus
}
#endif

#endif
