/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: host.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _HOST_H_
#define _HOST_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef hst__ns
#define hst__ns 900807046
#define hst__ns_id "http://tail-f.com/ns/example/host"
#define hst__ns_uri "http://tail-f.com/ns/example/host"
#endif

#define hst_name 1998270519
#define hst_ip 1643785435
#define hst_host 1711485895
#define hst_hosts 756968979

#ifdef __cplusplus
}
#endif

#endif
