/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: dhcp.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _DHCP_H_
#define _DHCP_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef dhcp__ns
#define dhcp__ns 27468984
#define dhcp__ns_id "http://yang-central.org/ns/example/dhcp"
#define dhcp__ns_uri "http://yang-central.org/ns/example/dhcp"
#endif

#define dhcp_ethernet 0
#define dhcp_syncHardwareClock 1508603283
#define dhcp_name 1998270519
#define dhcp_subnet 1544472008
#define dhcp_utc 1427039597
#define dhcp_range 28853268
#define dhcp_starts 1691002757
#define dhcp_dhcp 990408299
#define dhcp_net 872020178
#define dhcp_high 1521500897
#define dhcp_fddi 2
#define dhcp_leases 786131947
#define dhcp_token_ring 1
#define dhcp_shared_networks 511577759
#define dhcp_shared_network 256078062
#define dhcp_hardware 437223233
#define dhcp_domain_name 1601118986
#define dhcp_dynamic_bootp 29929361
#define dhcp_router 532320551
#define dhcp_dhcp_options 1182804749
#define dhcp_address 1266954393
#define dhcp_systemClock 1277209175
#define dhcp_max_lease_time 1794251668
#define dhcp_low 831859092
#define dhcp_status 1950810920
#define dhcp_hardwareClock 79967135
#define dhcp_type 2040883914
#define dhcp_clockSettings 161161467
#define dhcp_set_clock 910650654
#define dhcp_default_lease_time 1186076854
#define dhcp_ends 280193168
#define dhcp__actionpointid_actions "actions"

#ifdef __cplusplus
}
#endif

#endif
