/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: hooks.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _HOOKS_H_
#define _HOOKS_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef hooks__ns
#define hooks__ns 2063667187
#define hooks__ns_id "http://tail-f.com/ns/example/hooks"
#define hooks__ns_uri "http://tail-f.com/ns/example/hooks"
#endif

#define hooks_name 1998270519
#define hooks_ip 1643785435
#define hooks_hosts_ipv6 289261272
#define hooks_pathno 787960260
#define hooks_gw 207753152
#define hooks_hosts 756968979
#define hooks_netmask 240292132
#define hooks__callpointid_ip_mask "ip_mask"
#define hooks__callpointid_trans_hosts "trans_hosts"

#ifdef __cplusplus
}
#endif

#endif
