/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: hst.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _HST_H_
#define _HST_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef hst__ns
#define hst__ns 765803882
#define hst__ns_id "http://tail-f.com/ns/example/hst"
#define hst__ns_uri "http://tail-f.com/ns/example/hst"
#endif

#define hst_enabled 197426095
#define hst_name 1998270519
#define hst_interface 221572658
#define hst_defgw 1238966432
#define hst_mask 1167181041
#define hst_ip 1643785435
#define hst_host 1711485895
#define hst_domain 2003714718
#define hst_hosts 756968979
#define hst_interfaces 321503962
#define hst__callpointid_hcp "hcp"
#define hst__callpointid_icp "icp"

#ifdef __cplusplus
}
#endif

#endif
