/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: data.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _DATA_H_
#define _DATA_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef data__ns
#define data__ns 1063116700
#define data__ns_id "http://tail-f.com/ns/example/data"
#define data__ns_uri "http://tail-f.com/ns/example/data"
#endif

#define data_name 1998270519
#define data_utc 1427039597
#define data_description 202559156
#define data_microseconds 1799759438
#define data_mysubmode 783546478
#define data_data 535242711
#define data_seconds 1442107370
#define data__actionpointid_mode_name "mode_name"
#define data__callpointid_clock "clock"

#ifdef __cplusplus
}
#endif

#endif
