/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: arpe.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _ARPE_H_
#define _ARPE_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef arpe__ns
#define arpe__ns 1561036191
#define arpe__ns_id "http://tail-f.com/ns/example/arpe"
#define arpe__ns_uri "http://tail-f.com/ns/example/arpe"
#endif

#define arpe_ifname 404192533
#define arpe_arpe 417671722
#define arpe_arpentries 230872026
#define arpe_ip 1643785435
#define arpe_permanent 828170346
#define arpe_hwaddr 1315344465
#define arpe_published 1638777694
#define arpe__callpointid_arpe "arpe"

#ifdef __cplusplus
}
#endif

#endif
