/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ietf-ipv6-unicast-routing.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _IETF_IPV6_UNICAST_ROUTING_H_
#define _IETF_IPV6_UNICAST_ROUTING_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef v6ur__ns
#define v6ur__ns 1148518732
#define v6ur__ns_id "urn:ietf:params:xml:ns:yang:ietf-ipv6-unicast-routing"
#define v6ur__ns_uri "urn:ietf:params:xml:ns:yang:ietf-ipv6-unicast-routing"
#endif

#define v6ur_next_hop_options 799132675
#define v6ur_prefix 1408440115
#define v6ur_simple_next_hop 1473181152
#define v6ur_retrans_timer 1787894280
#define v6ur_cur_hop_limit 1787387145
#define v6ur_min_rtr_adv_interval 1087041657
#define v6ur_receive 3
#define v6ur_prohibit 2
#define v6ur_index 827593980
#define v6ur_route 2058743578
#define v6ur_next_hop 1889650088
#define v6ur_prefix_spec 2103199751
#define v6ur_advertise 1735966266
#define v6ur_special_next_hop 1009648386
#define v6ur_next_hop_address 88257637
#define v6ur_unreachable 1
#define v6ur_destination_address 1799113401
#define v6ur_other_config_flag 1035775729
#define v6ur_default_lifetime 1514554806
#define v6ur_description 202559156
#define v6ur_control_adv_prefixes 1116327960
#define v6ur_ipv6_unicast 540616510
#define v6ur_link_mtu 770656342
#define v6ur_valid_lifetime 1840441773
#define v6ur_blackhole 0
#define v6ur_managed_flag 597194005
#define v6ur_reachable_time 295458734
#define v6ur_destination_prefix 607480768
#define v6ur_prefix_list 1573095890
#define v6ur_no_advertise 1716278262
#define v6ur_ipv6 1228132394
#define v6ur_outgoing_interface 327758705
#define v6ur_send_advertisements 993827988
#define v6ur_preferred_lifetime 2084059856
#define v6ur_autonomous_flag 1460329517
#define v6ur_address 1266954393
#define v6ur_next_hop_list 1281346606
#define v6ur_on_link_flag 784688807
#define v6ur_max_rtr_adv_interval 1336607841
#define v6ur_ipv6_router_advertisements 225702719

#ifdef __cplusplus
}
#endif

#endif
