/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ietf-routing.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _IETF_ROUTING_H_
#define _IETF_ROUTING_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef rt__ns
#define rt__ns 971020673
#define rt__ns_id "urn:ietf:params:xml:ns:yang:ietf-routing"
#define rt__ns_uri "urn:ietf:params:xml:ns:yang:ietf-routing"
#endif

#define rt_next_hop_options 799132675
#define rt_simple_next_hop 1473181152
#define rt_default_rib 661062384
#define rt_receive 3
#define rt_active_route 887114465
#define rt_prohibit 2
#define rt_route 2058743578
#define rt_next_hop 1889650088
#define rt_name 1998270519
#define rt_interface 221572658
#define rt_routing_protocol 667412728
#define rt_static_routes 886355725
#define rt_special_next_hop 1009648386
#define rt_ribs 119293447
#define rt_address_family 203507431
#define rt_router_id 519485925
#define rt_unreachable 1
#define rt_last_updated 1398017376
#define rt_routing_state 1614158706
#define rt_source_protocol 206937218
#define rt_description 202559156
#define rt_ipv4 268057062
#define rt_control_plane_protocol 1785486143
#define rt_blackhole 0
#define rt_routes 278551890
#define rt_ipv6 1228132394
#define rt_rib 1033831672
#define rt_outgoing_interface 327758705
#define rt_direct 552814698
#define rt_next_hop_list 1281346606
#define rt_control_plane_protocols 582327772
#define rt_static 1504445999
#define rt_route_preference 462820766
#define rt_interfaces 321503962
#define rt_type 2040883914
#define rt_routing 1124806331
#define rt_active 124277386
#define rt__actionpointid_routing_state_active_route "routing_state_active_route"
#define rt__callpointid_routing_state_dp "routing_state_dp"

#ifdef __cplusplus
}
#endif

#endif
