/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ietf-ipv4-unicast-routing.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _IETF_IPV4_UNICAST_ROUTING_H_
#define _IETF_IPV4_UNICAST_ROUTING_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef v4ur__ns
#define v4ur__ns 664402674
#define v4ur__ns_id "urn:ietf:params:xml:ns:yang:ietf-ipv4-unicast-routing"
#define v4ur__ns_uri "urn:ietf:params:xml:ns:yang:ietf-ipv4-unicast-routing"
#endif

#define v4ur_next_hop_options 799132675
#define v4ur_simple_next_hop 1473181152
#define v4ur_receive 3
#define v4ur_prohibit 2
#define v4ur_index 827593980
#define v4ur_route 2058743578
#define v4ur_next_hop 1889650088
#define v4ur_special_next_hop 1009648386
#define v4ur_next_hop_address 88257637
#define v4ur_unreachable 1
#define v4ur_destination_address 1799113401
#define v4ur_description 202559156
#define v4ur_ipv4 268057062
#define v4ur_ipv4_unicast 2018585830
#define v4ur_blackhole 0
#define v4ur_destination_prefix 607480768
#define v4ur_outgoing_interface 327758705
#define v4ur_address 1266954393
#define v4ur_next_hop_list 1281346606

#ifdef __cplusplus
}
#endif

#endif
