//>>built
define("dojox/charting/plot2d/Bars","dojo/_base/lang dojo/_base/array dojo/_base/declare dojo/has ./CartesianBase ./_PlotEvents ./common dojox/gfx/fx dojox/lang/utils dojox/lang/functional dojox/lang/functional/reversed dojox/gfx/gradutils".split(" "),function(t,z,B,C,D,E,u,F,v,G,H,I){function w(){return!1}var J=H.lambda("item.purgeGroup()");return B("dojox.charting.plot2d.Bars",[D,E],{defaultParams:{gap:0,animate:null,enableCache:!1},optionalParams:{minBarSize:1,maxBarSize:1,minWidth:0,stroke:{},
outline:{},shadow:{},fill:{},filter:{},styleFunc:null,font:"",fontColor:""},constructor:function(a,b){this.opt=t.clone(t.mixin(this.opt,this.defaultParams));v.updateWithObject(this.opt,b);v.updateWithPattern(this.opt,b,this.optionalParams);this.animate=this.opt.animate},getSeriesStats:function(){var a=u.collectSimpleStats(this.series,t.hitch(this,"isNullValue")),b;a.hmin-=0.5;a.hmax+=0.5;b=a.hmin;a.hmin=a.vmin;a.vmin=b;b=a.hmax;a.hmax=a.vmax;a.vmax=b;return a},createRect:function(a,b,c){var d;this.opt.enableCache&&
0<a._rectFreePool.length?(d=a._rectFreePool.pop(),d.setShape(c),b.add(d)):d=b.createRect(c);this.opt.enableCache&&a._rectUsePool.push(d);return d},createLabel:function(a,b,c,d){this.opt.labels&&"outside"==this.opt.labelStyle?this.renderLabel(a,c.x+c.width+this.opt.labelOffset,c.y+c.height/2,this._getLabel(isNaN(b.y)?b:b.y),d,"start"):this.inherited(arguments)},render:function(a,b){if(this.zoom&&!this.isDataDirty())return this.performZoom(a,b);this.dirty=this.isDirty();this.resetEvents();var c;this.dirty&&
(z.forEach(this.series,J),this._eventSeries={},this.cleanGroup(),c=this.getGroup(),G.forEachRev(this.series,function(a){a.cleanGroup(c)}));for(var d=this.chart.theme,h=this._hScaler.scaler.getTransformerFromModel(this._hScaler),k=this._vScaler.scaler.getTransformerFromModel(this._vScaler),g=Math.max(this._hScaler.bounds.lower,this._hAxis?this._hAxis.naturalBaseline:0),g=h(g),n=this.events(),p=this.getBarProperties(),A=this.extractValues(this._vScaler),A=this.rearrangeValues(A,h,g),h=0;h<this.series.length;h++){var e=
this.series[h];if(!this.dirty&&!e.dirty)d.skip(),this._reconnectEvents(e.name);else{e.cleanGroup();this.opt.enableCache&&(e._rectFreePool=(e._rectFreePool?e._rectFreePool:[]).concat(e._rectUsePool?e._rectUsePool:[]),e._rectUsePool=[]);var u=d.next("bar",[this.opt,e]),v=Array(e.data.length);c=e.group;for(var x=z.some(e.data,function(a){return"number"==typeof a||a&&!a.hasOwnProperty("x")}),r=x?Math.max(0,Math.floor(this._vScaler.bounds.from-1)):0,x=x?Math.min(e.data.length,Math.ceil(this._vScaler.bounds.to)):
e.data.length;r<x;++r){var f=e.data[r];if(!this.isNullValue(f)){var s="number"==typeof f||isNaN(f.x)?r:f.x-1,w="number"==typeof f?f:f.y,y=A[h][r],q;if(this.opt.styleFunc||"number"!=typeof f){var l="number"!=typeof f?[f]:[];this.opt.styleFunc&&l.push(this.opt.styleFunc(f));f=d.addMixin(u,"bar",l,!0)}else f=d.post(u,"bar");if(0<=p.height){l={x:b.l+g+Math.min(y,0),y:a.height-b.b-k(s+1.5)+p.gap+p.thickness*(this.series.length-h-1),width:Math.abs(y),height:p.height};f.series.shadow&&(q=t.clone(l),q.x+=
f.series.shadow.dx,q.y+=f.series.shadow.dy,q=this.createRect(e,c,q).setFill(f.series.shadow.color).setStroke(f.series.shadow),this.animate&&this._animateBar(q,b.l+g,-Math.abs(y)));var m=f.series.fill;0>s&&m&&("linear"===m.type&&m.colors&&2===m.colors.length)&&(m=I.reverse(m));m=this._plotFill(m,a,b);m=this._shapeFill(m,l);l=this.createRect(e,c,l).setFill(m).setStroke(f.series.stroke);l.setFilter&&f.series.filter&&l.setFilter(f.series.filter);e.dyn.fill=l.getFill();e.dyn.stroke=l.getStroke();n&&(s=
{element:"bar",index:r,run:e,shape:l,shadow:q,x:w,y:s+1.5},this._connectEvents(s),v[r]=s);this.animate&&this._animateBar(l,b.l+g,-Math.abs(y))}}}this._eventSeries[e.name]=v;e.dirty=!1}}this.dirty=!1;C("dojo-bidi")&&this._checkOrientation(this.getGroup(),a,b);return this},extractValues:function(a){for(var b=[],c=this.series.length-1;0<=c;--c){var d=this.series[c];if(this.dirty||d.dirty){var h=z.some(d.data,function(a){return"number"==typeof a||a&&!a.hasOwnProperty("x")}),k=h?Math.max(0,Math.floor(a.bounds.from-
1)):0,h=h?Math.min(d.data.length,Math.ceil(a.bounds.to)):d.data.length,g=b[c]=[];g.min=k;for(g.max=h;k<h;++k){var n=d.data[k];g[k]=this.isNullValue(n)?0:"number"==typeof n?n:n.y}}}return b},rearrangeValues:function(a,b,c){for(var d=0,h=a.length;d<h;++d){var k=a[d];if(k)for(var g=k.min,n=k.max;g<n;++g){var p=k[g];k[g]=this.isNullValue(p)?0:b(p)-c}}if(this.opt.minWidth){b=this.opt.minWidth;d=0;for(h=a.length;d<h;++d)if(k=a[d]){g=k.min;for(n=k.max;g<n;++g)p=k[g],0<p&&p<b&&(k[g]=b)}}return a},isNullValue:function(a){if(null===
a||"undefined"==typeof a)return!0;var b=this._hAxis?this._hAxis.isNullValue:w,c=this._vAxis?this._vAxis.isNullValue:w;return"number"==typeof a?c(0.5)||b(a):c(isNaN(a.x)?0.5:a.x+0.5)||null===a.y||b(a.y)},getBarProperties:function(){var a=u.calculateBarSize(this._vScaler.bounds.scale,this.opt);return{gap:a.gap,height:a.size,thickness:0}},_animateBar:function(a,b,c){0==c&&(c=1);F.animateTransform(t.delegate({shape:a,duration:1200,transform:[{name:"translate",start:[b-b/c,0],end:[0,0]},{name:"scale",
start:[1/c,1],end:[1,1]},{name:"original"}]},this.animate)).play()}})});
//# sourceMappingURL=Bars.js.map