//>>built
define("dojox/charting/Chart","../main dojo/_base/lang dojo/_base/array dojo/_base/declare dojo/dom-style dojo/dom dojo/dom-geometry dojo/dom-construct dojo/_base/Color dojo/sniff ./Element ./SimpleTheme ./Series ./axis2d/common dojox/gfx/shape dojox/gfx dojo/has!dojo-bidi?./bidi/Chart dojox/lang/functional dojox/lang/functional/fold dojox/lang/functional/reversed".split(" "),function(q,y,g,z,r,G,n,A,B,p,k,H,I,C,D,m,J,e){function E(a,b){a&&b&&(a.min=Math.min(a.min,b.min),a.max=Math.max(a.max,b.max));
return a||b}function s(a,b){var c={},d={};g.forEach(a,function(a){var b=c[a.name]=a.getSeriesStats();a.hAxis&&(d[a.hAxis]=E(d[a.hAxis],{min:b.hmin,max:b.hmax}));a.vAxis&&(d[a.vAxis]=E(d[a.vAxis],{min:b.vmin,max:b.vmax}))});g.forEach(a,function(a){var h=c[a.name];if(a.hAxis){var e=d[a.hAxis];h.hmin=e.min;h.hmax=e.max}a.vAxis&&(e=d[a.vAxis],h.vmin=e.min,h.vmax=e.max);a.initializeScalers(b,h)})}var l=y.getObject("charting",!0,q),t=e.lambda("item.clear()"),u=e.lambda("item.purgeGroup()"),v=e.lambda("item.destroy()"),
w=e.lambda("item.dirty \x3d false"),x=e.lambda("item.dirty \x3d true"),F=e.lambda("item.name");defaultMargins={l:10,t:10,r:10,b:10};q=z(p("dojo-bidi")?"dojox.charting.NonBidiChart":"dojox.charting.Chart",null,{constructor:function(a,b){b||(b={});this.margins=b.margins||defaultMargins;this.customMargins=!!b.margins;this.margins=b.margins?b.margins:{l:10,t:10,r:10,b:10};this.stroke=b.stroke;this.fill=b.fill;this.delayInMs=b.delayInMs||200;this.title=b.title;this.titleGap=b.titleGap;this.titlePos=b.titlePos;
this.titleFont=b.titleFont;this.titleFontColor=b.titleFontColor;this.chartTitle=null;this.htmlLabels=!0;"htmlLabels"in b&&(this.htmlLabels=b.htmlLabels);this.theme=null;this.axes={};this.stack=[];this.plots={};this.series=[];this.runs={};this.dirty=!0;this.node=G.byId(a);var c=n.getMarginBox(a);this.surface=m.createSurface(this.node,c.w||400,c.h||300);-1==this.surface.declaredClass.indexOf("vml")&&(this._nativeClip=!0)},destroy:function(){g.forEach(this.series,v);g.forEach(this.stack,v);e.forIn(this.axes,
v);this.surface.destroy();this.chartTitle&&this.chartTitle.tagName&&A.destroy(this.chartTitle)},getCoords:function(){var a=this.node,b=r.getComputedStyle(a),b=n.getMarginBox(a,b),a=n.position(a,!0);b.x=a.x;b.y=a.y;return b},setTheme:function(a){this.theme=a.clone();this.customMargins||(this.margins=this.theme.chart.margins||defaultMargins);this.dirty=!0;return this},addAxis:function(a,b){var c;c=b&&b.type||"Default";if("string"==typeof c){if(!l.axis2d||!l.axis2d[c])throw Error("Can't find axis: "+
c+" - Check require() dependencies.");c=new l.axis2d[c](this,b)}else c=new c(this,b);c.name=a;c.dirty=!0;a in this.axes&&this.axes[a].destroy();this.axes[a]=c;this.dirty=!0;return this},getAxis:function(a){return this.axes[a]},removeAxis:function(a){a in this.axes&&(this.axes[a].destroy(),delete this.axes[a],this.dirty=!0);return this},addPlot:function(a,b){var c;c=b&&b.type||"Default";if("string"==typeof c){if(!l.plot2d||!l.plot2d[c])throw Error("Can't find plot: "+c+" - didn't you forget to dojo.require() it?");
c=new l.plot2d[c](this,b)}else c=new c(this,b);c.name=a;c.dirty=!0;a in this.plots?(this.stack[this.plots[a]].destroy(),this.stack[this.plots[a]]=c):(this.plots[a]=this.stack.length,this.stack.push(c));this.dirty=!0;return this},getPlot:function(a){return this.stack[this.plots[a]]},removePlot:function(a){if(a in this.plots){var b=this.plots[a];delete this.plots[a];this.stack[b].destroy();this.stack.splice(b,1);e.forIn(this.plots,function(a,c,h){a>b&&(h[c]=a-1)});var c=g.filter(this.series,function(b){return b.plot!=
a});c.length<this.series.length&&(g.forEach(this.series,function(b){b.plot==a&&b.destroy()}),this.runs={},g.forEach(c,function(a,b){this.runs[a.plot]=b},this),this.series=c);this.dirty=!0}return this},getPlotOrder:function(){return e.map(this.stack,F)},setPlotOrder:function(a){var b={},c=e.filter(a,function(a){if(!(a in this.plots)||a in b)return!1;b[a]=1;return!0},this);c.length<this.stack.length&&e.forEach(this.stack,function(a){a=a.name;a in b||c.push(a)});a=e.map(c,function(a){return this.stack[this.plots[a]]},
this);e.forEach(a,function(a,b){this.plots[a.name]=b},this);this.stack=a;this.dirty=!0;return this},movePlotToFront:function(a){if(a in this.plots){var b=this.plots[a];if(b){var c=this.getPlotOrder();c.splice(b,1);c.unshift(a);return this.setPlotOrder(c)}}return this},movePlotToBack:function(a){if(a in this.plots){var b=this.plots[a];if(b<this.stack.length-1){var c=this.getPlotOrder();c.splice(b,1);c.push(a);return this.setPlotOrder(c)}}return this},addSeries:function(a,b,c){b=new I(this,b,c);b.name=
a;a in this.runs?(this.series[this.runs[a]].destroy(),this.series[this.runs[a]]=b):(this.runs[a]=this.series.length,this.series.push(b));this.dirty=!0;!("ymin"in b)&&"min"in b&&(b.ymin=b.min);!("ymax"in b)&&"max"in b&&(b.ymax=b.max);return this},getSeries:function(a){return this.series[this.runs[a]]},removeSeries:function(a){if(a in this.runs){var b=this.runs[a];delete this.runs[a];this.series[b].destroy();this.series.splice(b,1);e.forIn(this.runs,function(a,d,f){a>b&&(f[d]=a-1)});this.dirty=!0}return this},
updateSeries:function(a,b,c){a in this.runs&&(a=this.series[this.runs[a]],a.update(b),c?this.dirty=!0:(this._invalidateDependentPlots(a.plot,!1),this._invalidateDependentPlots(a.plot,!0)));return this},getSeriesOrder:function(a){return e.map(e.filter(this.series,function(b){return b.plot==a}),F)},setSeriesOrder:function(a){var b,c={},d=e.filter(a,function(a){if(!(a in this.runs)||a in c)return!1;var d=this.series[this.runs[a]];if(b){if(d.plot!=b)return!1}else b=d.plot;c[a]=1;return!0},this);e.forEach(this.series,
function(a){var h=a.name;!(h in c)&&a.plot==b&&d.push(h)});this.series=e.map(d,function(a){return this.series[this.runs[a]]},this).concat(e.filter(this.series,function(a){return a.plot!=b}));e.forEach(this.series,function(a,b){this.runs[a.name]=b},this);this.dirty=!0;return this},moveSeriesToFront:function(a){if(a in this.runs){var b=this.runs[a],c=this.getSeriesOrder(this.series[b].plot);if(a!=c[0])return c.splice(b,1),c.unshift(a),this.setSeriesOrder(c)}return this},moveSeriesToBack:function(a){if(a in
this.runs){var b=this.runs[a],c=this.getSeriesOrder(this.series[b].plot);if(a!=c[c.length-1])return c.splice(b,1),c.push(a),this.setSeriesOrder(c)}return this},resize:function(a,b){switch(arguments.length){case 1:n.setMarginBox(this.node,a);break;case 2:n.setMarginBox(this.node,{w:a,h:b})}var c=n.getMarginBox(this.node),d=this.surface.getDimensions();return d.width!=c.w||d.height!=c.h?(this.surface.setDimensions(c.w,c.h),this.dirty=!0,this.render()):this},getGeometry:function(){var a={};e.forIn(this.axes,
function(b){b.initialized()&&(a[b.name]={name:b.name,vertical:b.vertical,scaler:b.scaler,ticks:b.ticks})});return a},setAxisWindow:function(a,b,c,d){var f=this.axes[a];f&&(f.setWindow(b,c),g.forEach(this.stack,function(b){if(b.hAxis==a||b.vAxis==a)b.zoom=d}));return this},setWindow:function(a,b,c,d,f){"plotArea"in this||this.calculateGeometry();e.forIn(this.axes,function(f){var e,g;e=f.getScaler().bounds;g=e.span/(e.upper-e.lower);f.vertical?(e=b,g=d/g/e):(e=a,g=c/g/e);f.setWindow(e,g)});g.forEach(this.stack,
function(a){a.zoom=f});return this},zoomIn:function(a,b,c){var d=this.axes[a];if(d){var d=d.getScaler().bounds,f=Math.min(b[0],b[1]),e=Math.max(b[0],b[1]),f=b[0]<d.lower?d.lower:f,e=b[1]>d.upper?d.upper:e;this.setAxisWindow(a,(d.upper-d.lower)/(e-f),f-d.lower);c?this.delayedRender():this.render()}},calculateGeometry:function(){if(this.dirty)return this.fullGeometry();var a=g.filter(this.stack,function(a){return a.dirty||a.hAxis&&this.axes[a.hAxis].dirty||a.vAxis&&this.axes[a.vAxis].dirty},this);s(a,
this.plotArea);return this},fullGeometry:function(){this._makeDirty();g.forEach(this.stack,t);this.theme||this.setTheme(new H);g.forEach(this.series,function(a){if(!(a.plot in this.plots)){if(!l.plot2d||!l.plot2d.Default)throw Error("Can't find plot: Default - didn't you forget to dojo.require() it?");var b=new l.plot2d.Default(this,{});b.name=a.plot;this.plots[a.plot]=this.stack.length;this.stack.push(b)}this.stack[this.plots[a.plot]].addSeries(a)},this);g.forEach(this.stack,function(a){a.assignAxes&&
a.assignAxes(this.axes)},this);var a=this.dim=this.surface.getDimensions();a.width=m.normalizedLength(a.width);a.height=m.normalizedLength(a.height);e.forIn(this.axes,t);s(this.stack,a);var b=this.offsets={l:0,r:0,t:0,b:0},c=this;e.forIn(this.axes,function(a){p("dojo-bidi")&&c._resetLeftBottom(a);e.forIn(a.getOffsets(),function(a,c){b[c]=Math.max(a,b[c])})});if(this.title){this.titleGap=0==this.titleGap?0:this.titleGap||this.theme.chart.titleGap||20;this.titlePos=this.titlePos||this.theme.chart.titlePos||
"top";this.titleFont=this.titleFont||this.theme.chart.titleFont;this.titleFontColor=this.titleFontColor||this.theme.chart.titleFontColor||"black";var d=m.normalizedLength(m.splitFontString(this.titleFont).size);b["top"==this.titlePos?"t":"b"]+=d+this.titleGap}e.forIn(this.margins,function(a,c){b[c]+=a});this.plotArea={width:a.width-b.l-b.r,height:a.height-b.t-b.b};e.forIn(this.axes,t);s(this.stack,this.plotArea);return this},render:function(){this._delayedRenderHandle&&(clearTimeout(this._delayedRenderHandle),
this._delayedRenderHandle=null);this.theme&&this.theme.clear();if(this.dirty)return this.fullRender();this.calculateGeometry();e.forEachRev(this.stack,function(a){a.render(this.dim,this.offsets)},this);e.forIn(this.axes,function(a){a.render(this.dim,this.offsets)},this);this._makeClean();return this},fullRender:function(){this.fullGeometry();var a=this.offsets,b=this.dim,c=Math.max(0,b.width-a.l-a.r),d=Math.max(0,b.height-a.t-a.b);g.forEach(this.series,u);e.forIn(this.axes,u);g.forEach(this.stack,
u);var f=this.surface.children;if(D.dispose)for(var h=0;h<f.length;++h)D.dispose(f[h]);this.chartTitle&&this.chartTitle.tagName&&A.destroy(this.chartTitle);this.surface.clear();this.chartTitle=null;this._renderChartBackground(b,a);this._renderPlotBackground(b,a,c,d);e.foldr(this.stack,function(c,d){return d.render(b,a),0},0);this._nativeClip||this._renderChartBackground(b,a);this.title&&this._renderTitle(b,a);e.forIn(this.axes,function(c){c.render(b,a)});this._makeClean();return this},_renderTitle:function(a,
b){var c="canvas"==m.renderer&&this.htmlLabels||!p("ie")&&!p("opera")&&this.htmlLabels?"html":"gfx",d=m.normalizedLength(m.splitFontString(this.titleFont).size),f=this.theme,f=f&&f.chart&&f.chart.titleAlign||"middle";!f||"edge"!==f?this.chartTitle=C.createText[c](this,this.surface,a.width/2,"top"==this.titlePos?d+this.margins.t:a.height-this.margins.b,"middle",this.title,this.titleFont,this.titleFontColor):"edge"===f&&(this.chartTitle=C.createText[c](this,this.surface,b.l,"top"==this.titlePos?d+this.margins.t:
a.height-this.margins.b,"left",this.title,this.titleFont,this.titleFontColor))},_renderChartBackground:function(a,b){var c=this.theme,d,f=void 0!==this.fill?this.fill:c.chart&&c.chart.fill,c=void 0!==this.stroke?this.stroke:c.chart&&c.chart.stroke;if("inherit"==f){d=this.node;for(f=new B(r.get(d,"backgroundColor"));0==f.a&&d!=document.documentElement;)f=new B(r.get(d,"backgroundColor")),d=d.parentNode}f&&(this._nativeClip?(f=k.prototype._shapeFill(k.prototype._plotFill(f,a),{x:0,y:0,width:a.width+
1,height:a.height+1}),this.surface.createRect({width:a.width+1,height:a.height+1}).setFill(f)):(f=k.prototype._plotFill(f,a,b),b.l&&(d={x:0,y:0,width:b.l,height:a.height+1},this.surface.createRect(d).setFill(k.prototype._shapeFill(f,d))),b.r&&(d={x:a.width-b.r,y:0,width:b.r+1,height:a.height+2},this.surface.createRect(d).setFill(k.prototype._shapeFill(f,d))),b.t&&(d={x:0,y:0,width:a.width+1,height:b.t},this.surface.createRect(d).setFill(k.prototype._shapeFill(f,d))),b.b&&(d={x:0,y:a.height-b.b,width:a.width+
1,height:b.b+2},this.surface.createRect(d).setFill(k.prototype._shapeFill(f,d)))));c&&this.surface.createRect({width:a.width-1,height:a.height-1}).setStroke(c)},_renderPlotBackground:function(a,b,c,d){var f=this.theme,e=f.plotarea&&f.plotarea.fill,f=f.plotarea&&f.plotarea.stroke,g={x:b.l-1,y:b.t-1,width:c+2,height:d+2};e&&(e=k.prototype._shapeFill(k.prototype._plotFill(e,a,b),g),this.surface.createRect(g).setFill(e));f&&this.surface.createRect({x:b.l,y:b.t,width:c+1,height:d+1}).setStroke(f)},delayedRender:function(){this._delayedRenderHandle||
(this._delayedRenderHandle=setTimeout(y.hitch(this,function(){this.render()}),this.delayInMs));return this},connectToPlot:function(a,b,c){return a in this.plots?this.stack[this.plots[a]].connect(b,c):null},fireEvent:function(a,b,c){if(a in this.runs){var d=this.series[this.runs[a]].plot;d in this.plots&&(d=this.stack[this.plots[d]])&&d.fireEvent(a,b,c)}return this},_makeClean:function(){g.forEach(this.axes,w);g.forEach(this.stack,w);g.forEach(this.series,w);this.dirty=!1},_makeDirty:function(){g.forEach(this.axes,
x);g.forEach(this.stack,x);g.forEach(this.series,x);this.dirty=!0},_invalidateDependentPlots:function(a,b){if(a in this.plots){var c=this.stack[this.plots[a]],d,e=b?"vAxis":"hAxis";if(c[e]){if((d=this.axes[c[e]])&&d.dependOnData())d.dirty=!0,g.forEach(this.stack,function(a){a[e]&&a[e]==c[e]&&(a.dirty=!0)})}else c.dirty=!0}},setDir:function(a){return this},_resetLeftBottom:function(a){},formatTruncatedLabel:function(a,b,c){}});return p("dojo-bidi")?z("dojox.charting.Chart",[q,J]):q});
//# sourceMappingURL=Chart.js.map