/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: routes.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _ROUTES_H_
#define _ROUTES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef r__ns
#define r__ns 2062931146
#define r__ns_id "http://tail-f.com/ns/example/routes/1.0"
#define r__ns_uri "http://tail-f.com/ns/example/routes/1.0"
#endif

#define r_route 2058743578
#define r_id 1279252765
#define r_value 864367181
#define r_routes 278551890
#define r__callpointid_routescp "routescp"

#ifdef __cplusplus
}
#endif

#endif
