/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: notif.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _NOTIF_H_
#define _NOTIF_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef notif__ns
#define notif__ns 1945824463
#define notif__ns_id "http://tail-f.com/ns/test/notif"
#define notif__ns_uri "http://tail-f.com/ns/test/notif"
#endif

#define notif_newlyAdded 1939024431
#define notif_name 1998270519
#define notif_interface 221572658
#define notif_ifIndex 1909855274
#define notif_linkProperty 1724773219
#define notif_extensions 6037758
#define notif_extraId 1201642424
#define notif_value 864367181
#define notif_linkUp 1621884104
#define notif_interfaces 321503962
#define notif_linkDown 740290268
#define notif_flags 1646628167
#define notif_desc 1535721889

#ifdef __cplusplus
}
#endif

#endif
