/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/touch","./_base/kernel ./aspect ./dom ./dom-class ./_base/lang ./on ./has ./mouse ./domReady ./_base/window".split(" "),function(E,v,w,F,G,g,m,s,x,e){function l(c,b,a){return t&&a?function(c,b){return g(c,a,b)}:H?function(a,e){var d=g(a,b,function(d){e.call(this,d);n=(new Date).getTime()}),I=g(a,c,function(d){(!n||(new Date).getTime()>n+1E3)&&e.call(this,d)});return{remove:function(){d.remove();I.remove()}}}:function(b,a){return g(b,c,a)}}function J(c){do if(void 0!==c.dojoClick)return c;
while(c=c.parentNode)}function y(c,b,a){var f=J(c.target);if(h=!c.target.disabled&&f&&f.dojoClick)if(q=(p="useTarget"==h)?f:c.target,p&&c.preventDefault(),z=c.changedTouches?c.changedTouches[0].pageX-e.global.pageXOffset:c.clientX,A=c.changedTouches?c.changedTouches[0].pageY-e.global.pageYOffset:c.clientY,B=("object"==typeof h?h.x:"number"==typeof h?h:0)||4,C=("object"==typeof h?h.y:"number"==typeof h?h:0)||4,!D){D=!0;var k=function(d){h=p?w.isDescendant(e.doc.elementFromPoint(d.changedTouches?d.changedTouches[0].pageX-
e.global.pageXOffset:d.clientX,d.changedTouches?d.changedTouches[0].pageY-e.global.pageYOffset:d.clientY),q):h&&(d.changedTouches?d.changedTouches[0].target:d.target)==q&&Math.abs((d.changedTouches?d.changedTouches[0].pageX-e.global.pageXOffset:d.clientX)-z)<=B&&Math.abs((d.changedTouches?d.changedTouches[0].pageY-e.global.pageYOffset:d.clientY)-A)<=C};e.doc.addEventListener(b,function(d){k(d);p&&d.preventDefault()},!0);e.doc.addEventListener(a,function(d){k(d);if(h){u=(new Date).getTime();var b=
p?q:d.target;"LABEL"===b.tagName&&(b=w.byId(b.getAttribute("for"))||b);var c=d.changedTouches?d.changedTouches[0]:d,a=function(b){var a=document.createEvent("MouseEvents");a._dojo_click=!0;a.initMouseEvent(b,!0,!0,d.view,d.detail,c.screenX,c.screenY,c.clientX,c.clientY,d.ctrlKey,d.altKey,d.shiftKey,d.metaKey,0,null);return a},e=a("mousedown"),f=a("mouseup"),l=a("click");setTimeout(function(){g.emit(b,"mousedown",e);g.emit(b,"mouseup",f);g.emit(b,"click",l);u=(new Date).getTime()},0)}},!0);c=function(b){e.doc.addEventListener(b,
function(a){!a._dojo_click&&((new Date).getTime()<=u+1E3&&!("INPUT"==a.target.tagName&&F.contains(a.target,"dijitOffScreen")))&&(a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),"click"==b&&(("INPUT"!=a.target.tagName||"radio"==a.target.type||"checkbox"==a.target.type)&&"TEXTAREA"!=a.target.tagName&&"AUDIO"!=a.target.tagName&&"VIDEO"!=a.target.tagName)&&a.preventDefault())},!0)};c("click");c("mousedown");c("mouseup")}}var r=5>m("ios"),t=m("pointer-events")||m("MSPointer"),
f=function(){var c={},b;for(b in{down:1,move:1,up:1,cancel:1,over:1,out:1})c[b]=m("MSPointer")?"MSPointer"+b.charAt(0).toUpperCase()+b.slice(1):"pointer"+b;return c}(),H=m("touch-events"),D,h,p=!1,q,z,A,B,C,u,n,k;m("touch")&&(t?x(function(){e.doc.addEventListener(f.down,function(c){y(c,f.move,f.up)},!0)}):x(function(){function c(b){var a=G.delegate(b,{bubbles:!0});6<=m("ios")&&(a.touches=b.touches,a.altKey=b.altKey,a.changedTouches=b.changedTouches,a.ctrlKey=b.ctrlKey,a.metaKey=b.metaKey,a.shiftKey=
b.shiftKey,a.targetTouches=b.targetTouches);return a}k=e.body();e.doc.addEventListener("touchstart",function(b){n=(new Date).getTime();var a=k;k=b.target;g.emit(a,"dojotouchout",{relatedTarget:k,bubbles:!0});g.emit(k,"dojotouchover",{relatedTarget:a,bubbles:!0});y(b,"touchmove","touchend")},!0);g(e.doc,"touchmove",function(b){n=(new Date).getTime();var a=e.doc.elementFromPoint(b.pageX-(r?0:e.global.pageXOffset),b.pageY-(r?0:e.global.pageYOffset));a&&(k!==a&&(g.emit(k,"dojotouchout",{relatedTarget:a,
bubbles:!0}),g.emit(a,"dojotouchover",{relatedTarget:k,bubbles:!0}),k=a),g.emit(a,"dojotouchmove",c(b))||b.preventDefault())});g(e.doc,"touchend",function(b){n=(new Date).getTime();var a=e.doc.elementFromPoint(b.pageX-(r?0:e.global.pageXOffset),b.pageY-(r?0:e.global.pageYOffset))||e.body();g.emit(a,"dojotouchend",c(b))})}));v={press:l("mousedown","touchstart",f.down),move:l("mousemove","dojotouchmove",f.move),release:l("mouseup","dojotouchend",f.up),cancel:l(s.leave,"touchcancel",t?f.cancel:null),
over:l("mouseover","dojotouchover",f.over),out:l("mouseout","dojotouchout",f.out),enter:s._eventHandler(l("mouseover","dojotouchover",f.over)),leave:s._eventHandler(l("mouseout","dojotouchout",f.out))};return E.touch=v});
//# sourceMappingURL=touch.js.map