/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

/*
	This is an optimized version of Dojo, built for deployment and not for
	development. To get sources and documentation, please visit:

		http://dojotoolkit.org
*/

//>>built
require({cache:{"dojo/request/default":function(){define(["exports","require","../has"],function(m,k,h){var l=h("config-requestProvider");l||(l="./xhr");m.getPlatformDefaultId=function(){return"./xhr"};m.load=function(f,a,d,g){k(["platform"==f?"./xhr":l],function(a){d(a)})}})},"dijit/popup":function(){define("dojo/_base/array dojo/aspect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/keys dojo/_base/lang dojo/on ./place ./BackgroundIframe ./Viewport ./main".split(" "),
function(m,k,h,l,f,a,d,g,c,e,b,s,x,v,r,n){function u(){this._popupWrapper&&(a.destroy(this._popupWrapper),delete this._popupWrapper)}h=h(null,{_stack:[],_beginZIndex:1E3,_idGen:1,_repositionAll:function(){if(this._firstAroundNode){var e=this._firstAroundPosition,a=d.position(this._firstAroundNode,!0),c=a.x-e.x,e=a.y-e.y;if(c||e){this._firstAroundPosition=a;for(a=0;a<this._stack.length;a++){var g=this._stack[a].wrapper.style;g.top=parseFloat(g.top)+e+"px";"auto"==g.right?g.left=parseFloat(g.left)+
c+"px":g.right=parseFloat(g.right)-c+"px"}}this._aroundMoveListener=setTimeout(b.hitch(this,"_repositionAll"),c||e?10:50)}},_createWrapper:function(b){var e=b._popupWrapper,c=b.domNode;e||(e=a.create("div",{"class":"dijitPopup",style:{display:"none"},role:"region","aria-label":b["aria-label"]||b.label||b.name||b.id},b.ownerDocumentBody),e.appendChild(c),c=c.style,c.display="",c.visibility="",c.position="",c.top="0px",b._popupWrapper=e,k.after(b,"destroy",u,!0),"ontouchend"in document&&s(e,"touchend",
function(b){/^(input|button|textarea)$/i.test(b.target.tagName)||b.preventDefault()}));return e},moveOffScreen:function(b){var e=this._createWrapper(b);b=d.isBodyLtr(b.ownerDocument);var a={visibility:"hidden",top:"-9999px",display:""};a[b?"left":"right"]="-9999px";a[b?"right":"left"]="auto";g.set(e,a);return e},hide:function(b){var e=this._createWrapper(b);g.set(e,{display:"none",height:"auto",overflow:"visible",border:""});b=b.domNode;"_originalStyle"in b&&(b.style.cssText=b._originalStyle)},getTopPopup:function(){for(var b=
this._stack,e=b.length-1;0<e&&b[e].parent===b[e-1].widget;e--);return b[e]},open:function(a){for(var h=this._stack,n=a.popup,k=n.domNode,m=a.orient||["below","below-alt","above","above-alt"],q=a.parent?a.parent.isLeftToRight():d.isBodyLtr(n.ownerDocument),F=a.around,u=a.around&&a.around.id?a.around.id+"_dropdown":"popup_"+this._idGen++;h.length&&(!a.parent||!l.isDescendant(a.parent.domNode,h[h.length-1].widget.domNode));)this.close(h[h.length-1].widget);var z=this.moveOffScreen(n);n.startup&&!n._started&&
n.startup();var H,I=d.position(k);if("maxHeight"in a&&-1!=a.maxHeight)H=a.maxHeight||Infinity;else{H=r.getEffectiveBox(this.ownerDocument);var M=F?d.position(F,!1):{y:a.y-(a.padding||0),h:2*(a.padding||0)};H=Math.floor(Math.max(M.y,H.h-(M.y+M.h)))}I.h>H&&(I=g.getComputedStyle(k),g.set(z,{overflowY:"scroll",height:H+"px",border:I.borderLeftWidth+" "+I.borderLeftStyle+" "+I.borderLeftColor}),k._originalStyle=k.style.cssText,k.style.border="none");f.set(z,{id:u,style:{zIndex:this._beginZIndex+h.length},
"class":"dijitPopup "+(n.baseClass||n["class"]||"").split(" ")[0]+"Popup",dijitPopupParent:a.parent?a.parent.id:""});0==h.length&&F&&(this._firstAroundNode=F,this._firstAroundPosition=d.position(F,!0),this._aroundMoveListener=setTimeout(b.hitch(this,"_repositionAll"),50));c("config-bgIframe")&&!n.bgIframe&&(n.bgIframe=new v(z));u=n.orient?b.hitch(n,"orient"):null;m=F?x.around(z,F,m,q,u):x.at(z,a,"R"==m?["TR","BR","TL","BL"]:["TL","BL","TR","BR"],a.padding,u);z.style.visibility="visible";k.style.visibility=
"visible";k=[];k.push(s(z,"keydown",b.hitch(this,function(b){if(b.keyCode==e.ESCAPE&&a.onCancel)b.stopPropagation(),b.preventDefault(),a.onCancel();else if(b.keyCode==e.TAB&&(b.stopPropagation(),b.preventDefault(),(b=this.getTopPopup())&&b.onCancel))b.onCancel()})));n.onCancel&&a.onCancel&&k.push(n.on("cancel",a.onCancel));k.push(n.on(n.onExecute?"execute":"change",b.hitch(this,function(){var b=this.getTopPopup();if(b&&b.onExecute)b.onExecute()})));h.push({widget:n,wrapper:z,parent:a.parent,onExecute:a.onExecute,
onCancel:a.onCancel,onClose:a.onClose,handlers:k});if(n.onOpen)n.onOpen(m);return m},close:function(b){for(var a=this._stack;b&&m.some(a,function(a){return a.widget==b})||!b&&a.length;){var e=a.pop(),c=e.widget,g=e.onClose;c.bgIframe&&(c.bgIframe.destroy(),delete c.bgIframe);if(c.onClose)c.onClose();for(var d;d=e.handlers.pop();)d.remove();c&&c.domNode&&this.hide(c);g&&g()}0==a.length&&this._aroundMoveListener&&(clearTimeout(this._aroundMoveListener),this._firstAroundNode=this._firstAroundPosition=
this._aroundMoveListener=null)}});return n.popup=new h})},"dojo/string":function(){define(["./_base/kernel","./_base/lang"],function(m,k){var h=/[&<>'"\/]/g,l={"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;","/":"\x26#x2F;"},f={};k.setObject("dojo.string",f);f.escape=function(a){return!a?"":a.replace(h,function(a){return l[a]})};f.rep=function(a,d){if(0>=d||!a)return"";for(var g=[];;){d&1&&g.push(a);if(!(d>>=1))break;a+=a}return g.join("")};f.pad=function(a,d,g,
c){g||(g="0");a=String(a);d=f.rep(g,Math.ceil((d-a.length)/g.length));return c?a+d:d+a};f.substitute=function(a,d,g,c){c=c||m.global;g=g?k.hitch(c,g):function(a){return a};return a.replace(/\$\{([^\s\:\}]+)(?:\:([^\s\:\}]+))?\}/g,function(a,b,s){a=k.getObject(b,!1,d);s&&(a=k.getObject(s,!1,c).call(c,a,b));return g(a,b).toString()})};f.trim=String.prototype.trim?k.trim:function(a){a=a.replace(/^\s+/,"");for(var d=a.length-1;0<=d;d--)if(/\S/.test(a.charAt(d))){a=a.substring(0,d+1);break}return a};return f})},
"dijit/a11y":function(){define("dojo/_base/array dojo/dom dojo/dom-attr dojo/dom-style dojo/_base/lang dojo/sniff ./main".split(" "),function(m,k,h,l,f,a,d){var g={_isElementShown:function(a){var e=l.get(a);return"hidden"!=e.visibility&&"collapsed"!=e.visibility&&"none"!=e.display&&"hidden"!=h.get(a,"type")},hasDefaultTabStop:function(a){switch(a.nodeName.toLowerCase()){case "a":return h.has(a,"href");case "area":case "button":case "input":case "object":case "select":case "textarea":return!0;case "iframe":var e;
try{var b=a.contentDocument;if("designMode"in b&&"on"==b.designMode)return!0;e=b.body}catch(g){try{e=a.contentWindow.document.body}catch(d){return!1}}return e&&("true"==e.contentEditable||e.firstChild&&"true"==e.firstChild.contentEditable);default:return"true"==a.contentEditable}},effectiveTabIndex:function(a){return h.get(a,"disabled")?void 0:h.has(a,"tabIndex")?+h.get(a,"tabIndex"):g.hasDefaultTabStop(a)?0:void 0},isTabNavigable:function(a){return 0<=g.effectiveTabIndex(a)},isFocusable:function(a){return-1<=
g.effectiveTabIndex(a)},_getTabNavigable:function(c){function e(b){return b&&"input"==b.tagName.toLowerCase()&&b.type&&"radio"==b.type.toLowerCase()&&b.name&&b.name.toLowerCase()}var b,d,f,v,l,n,k={},m=g._isElementShown,t=g.effectiveTabIndex,p=function(c){for(c=c.firstChild;c;c=c.nextSibling)if(!(1!=c.nodeType||9>=a("ie")&&"HTML"!==c.scopeName||!m(c))){var g=t(c);if(0<=g){if(0==g)b||(b=c),d=c;else if(0<g){if(!f||g<v)v=g,f=c;if(!l||g>=n)n=g,l=c}g=e(c);h.get(c,"checked")&&g&&(k[g]=c)}"SELECT"!=c.nodeName.toUpperCase()&&
p(c)}};m(c)&&p(c);return{first:k[e(b)]||b,last:k[e(d)]||d,lowest:k[e(f)]||f,highest:k[e(l)]||l}},getFirstInTabbingOrder:function(a,e){var b=g._getTabNavigable(k.byId(a,e));return b.lowest?b.lowest:b.first},getLastInTabbingOrder:function(a,e){var b=g._getTabNavigable(k.byId(a,e));return b.last?b.last:b.highest}};f.mixin(d,g);return g})},"dijit/WidgetSet":function(){define(["dojo/_base/array","dojo/_base/declare","dojo/_base/kernel","./registry"],function(m,k,h,l){var f=k("dijit.WidgetSet",null,{constructor:function(){this._hash=
{};this.length=0},add:function(a){if(this._hash[a.id])throw Error("Tried to register widget with id\x3d\x3d"+a.id+" but that id is already registered");this._hash[a.id]=a;this.length++},remove:function(a){this._hash[a]&&(delete this._hash[a],this.length--)},forEach:function(a,d){d=d||h.global;var g=0,c;for(c in this._hash)a.call(d,this._hash[c],g++,this._hash);return this},filter:function(a,d){d=d||h.global;var g=new f,c=0,e;for(e in this._hash){var b=this._hash[e];a.call(d,b,c++,this._hash)&&g.add(b)}return g},
byId:function(a){return this._hash[a]},byClass:function(a){var d=new f,g,c;for(g in this._hash)c=this._hash[g],c.declaredClass==a&&d.add(c);return d},toArray:function(){var a=[],d;for(d in this._hash)a.push(this._hash[d]);return a},map:function(a,d){return m.map(this.toArray(),a,d)},every:function(a,d){d=d||h.global;var g=0,c;for(c in this._hash)if(!a.call(d,this._hash[c],g++,this._hash))return!1;return!0},some:function(a,d){d=d||h.global;var g=0,c;for(c in this._hash)if(a.call(d,this._hash[c],g++,
this._hash))return!0;return!1}});m.forEach("forEach filter byClass map every some".split(" "),function(a){l[a]=f.prototype[a]});return f})},"dijit/_base/wai":function(){define(["dojo/dom-attr","dojo/_base/lang","../main","../hccss"],function(m,k,h){k.mixin(h,{hasWaiRole:function(h,f){var a=this.getWaiRole(h);return f?-1<a.indexOf(f):0<a.length},getWaiRole:function(h){return k.trim((m.get(h,"role")||"").replace("wairole:",""))},setWaiRole:function(h,f){m.set(h,"role",f)},removeWaiRole:function(h,f){var a=
m.get(h,"role");a&&(f?(a=k.trim((" "+a+" ").replace(" "+f+" "," ")),m.set(h,"role",a)):h.removeAttribute("role"))},hasWaiState:function(h,f){return h.hasAttribute?h.hasAttribute("aria-"+f):!!h.getAttribute("aria-"+f)},getWaiState:function(h,f){return h.getAttribute("aria-"+f)||""},setWaiState:function(h,f,a){h.setAttribute("aria-"+f,a)},removeWaiState:function(h,f){h.removeAttribute("aria-"+f)}});return h})},"dijit/Viewport":function(){define(["dojo/Evented","dojo/on","dojo/domReady","dojo/sniff",
"dojo/window"],function(m,k,h,l,f){var a=new m,d;h(function(){var g=f.getBox();a._rlh=k(window,"resize",function(){var e=f.getBox();g.h==e.h&&g.w==e.w||(g=e,a.emit("resize"))});if(8==l("ie")){var c=screen.deviceXDPI;setInterval(function(){screen.deviceXDPI!=c&&(c=screen.deviceXDPI,a.emit("resize"))},500)}l("ios")&&(k(document,"focusin",function(a){d=a.target}),k(document,"focusout",function(a){d=null}))});a.getEffectiveBox=function(a){a=f.getBox(a);var c=d&&d.tagName&&d.tagName.toLowerCase();if(l("ios")&&
d&&!d.readOnly&&("textarea"==c||"input"==c&&/^(color|email|number|password|search|tel|text|url)$/.test(d.type)))a.h*=0==orientation||180==orientation?0.66:0.4,c=d.getBoundingClientRect(),a.h=Math.max(a.h,c.top+c.height);return a};return a})},"dojo/hccss":function(){define("require ./_base/config ./dom-class ./dom-style ./has ./domReady ./_base/window".split(" "),function(m,k,h,l,f,a,d){f.add("highcontrast",function(){var a=d.doc.createElement("div");a.style.cssText='border: 1px solid; border-color:red green; position: absolute; height: 5px; top: -999px;background-image: url("'+
(k.blankGif||m.toUrl("./resources/blank.gif"))+'");';d.body().appendChild(a);var c=l.getComputedStyle(a),e=c.backgroundImage,c=c.borderTopColor==c.borderRightColor||e&&("none"==e||"url(invalid-url:)"==e);8>=f("ie")?a.outerHTML="":d.body().removeChild(a);return c});a(function(){f("highcontrast")&&h.add(d.body(),"dj_a11y")});return f})},"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),
function(m,k,h,l,f,a,d,g,c,e,b,s,x,v,r,n,u,y,t,p,w,D,q){function F(b){return function(a){g[a?"set":"remove"](this.domNode,b,a);this._set(b,a)}}x.add("dijit-legacy-requires",!v.isAsync);x.add("dojo-bidi",!1);x("dijit-legacy-requires")&&u(0,function(){m(["dijit/_base/manager"])});var E={};l=a("dijit._WidgetBase",[y,w],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:F("lang"),dir:"",_setDirAttr:F("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",
baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(b){this._set("ownerDocument",b)},attributeMap:{},_blankGif:l.blankGif||m.toUrl("dojo/resources/blank.gif"),_introspect:function(){var b=this.constructor;if(!b._setterAttrs){var a=b.prototype,e=b._setterAttrs=[],b=b._onMap={},c;for(c in a.attributeMap)e.push(c);for(c in a)/^on/.test(c)&&(b[c.substring(2).toLowerCase()]=c),/^_set[A-Z](.*)Attr$/.test(c)&&(c=c.charAt(4).toLowerCase()+c.substr(5,
c.length-9),(!a.attributeMap||!(c in a.attributeMap))&&e.push(c))}},postscript:function(b,a){this.create(b,a)},create:function(b,a){this._introspect();this.srcNodeRef=d.byId(a);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&"string"==typeof this.srcNodeRef.id&&(this.id=this.srcNodeRef.id);b&&(this.params=b,r.mixin(this,b));this.postMixInProperties();this.id||(this.id=q.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||
(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=p.body(this.ownerDocument);q.add(this);this.buildRendering();var c;if(this.domNode){this._applyAttributes();var e=this.srcNodeRef;e&&(e.parentNode&&this.domNode!==e)&&(e.parentNode.replaceChild(this.domNode,e),c=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();c&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var b={},a;for(a in this.params||{})b[a]=this._get(a);k.forEach(this.constructor._setterAttrs,
function(a){if(!(a in b)){var c=this._get(a);c&&this.set(a,c)}},this);for(a in b)this.set(a,b[a])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var b=this.baseClass.split(" ");this.isLeftToRight()||(b=b.concat(k.map(b,function(b){return b+"Rtl"})));c.add(this.domNode,b)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,k.forEach(this.getChildren(),function(b){!b._started&&
(!b._destroyed&&r.isFunction(b.startup))&&(b.startup(),b._started=!0)}))},destroyRecursive:function(b){this._beingDestroyed=!0;this.destroyDescendants(b);this.destroy(b)},destroy:function(b){function a(c){c.destroyRecursive?c.destroyRecursive(b):c.destroy&&c.destroy(b)}this._beingDestroyed=!0;this.uninitialize();k.forEach(this._connects,r.hitch(this,"disconnect"));k.forEach(this._supportingWidgets,a);this.domNode&&k.forEach(q.findWidgets(this.domNode,this.containerNode),a);this.destroyRendering(b);
q.remove(this.id);this._destroyed=!0},destroyRendering:function(b){this.bgIframe&&(this.bgIframe.destroy(b),delete this.bgIframe);this.domNode&&(b?g.remove(this.domNode,"widgetId"):e.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(b||e.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(b){k.forEach(this.getChildren(),function(a){a.destroyRecursive&&a.destroyRecursive(b)})},uninitialize:function(){return!1},_setStyleAttr:function(b){var a=this.domNode;r.isObject(b)?
s.set(a,b):a.style.cssText=a.style.cssText?a.style.cssText+("; "+b):b;this._set("style",b)},_attrToDom:function(b,a,e){e=3<=arguments.length?e:this.attributeMap[b];k.forEach(r.isArray(e)?e:[e],function(e){var d=this[e.node||e||"domNode"];switch(e.type||"attribute"){case "attribute":r.isFunction(a)&&(a=r.hitch(this,a));e=e.attribute?e.attribute:/^on[A-Z][a-zA-Z]*$/.test(b)?b.toLowerCase():b;d.tagName?g.set(d,e,a):d.set(e,a);break;case "innerText":d.innerHTML="";d.appendChild(this.ownerDocument.createTextNode(a));
break;case "innerHTML":d.innerHTML=a;break;case "class":c.replace(d,a,this[b])}},this)},get:function(b){var a=this._getAttrNames(b);return this[a.g]?this[a.g]():this._get(b)},set:function(b,a){if("object"===typeof b){for(var e in b)this.set(e,b[e]);return this}e=this._getAttrNames(b);var c=this[e.s];if(r.isFunction(c))var d=c.apply(this,Array.prototype.slice.call(arguments,1));else{var c=this.focusNode&&!r.isFunction(this.focusNode)?"focusNode":"domNode",g=this[c]&&this[c].tagName,f;if(f=g)if(!(f=
E[g])){f=this[c];var s={},x;for(x in f)s[x.toLowerCase()]=!0;f=E[g]=s}x=f;e=b in this.attributeMap?this.attributeMap[b]:e.s in this?this[e.s]:x&&e.l in x&&"function"!=typeof a||/^aria-|^data-|^role$/.test(b)?c:null;null!=e&&this._attrToDom(b,a,e);this._set(b,a)}return d||this},_attrPairNames:{},_getAttrNames:function(b){var a=this._attrPairNames;if(a[b])return a[b];var e=b.replace(/^[a-z]|-[a-zA-Z]/g,function(b){return b.charAt(b.length-1).toUpperCase()});return a[b]={n:b+"Node",s:"_set"+e+"Attr",
g:"_get"+e+"Attr",l:e.toLowerCase()}},_set:function(b,a){var e=this[b];this[b]=a;if(this._created&&!(e===a||e!==e&&a!==a))this._watchCallbacks&&this._watchCallbacks(b,e,a),this.emit("attrmodified-"+b,{detail:{prevValue:e,newValue:a}})},_get:function(b){return this[b]},emit:function(b,a,e){a=a||{};void 0===a.bubbles&&(a.bubbles=!0);void 0===a.cancelable&&(a.cancelable=!0);a.detail||(a.detail={});a.detail.widget=this;var c,d=this["on"+b];d&&(c=d.apply(this,e?e:[a]));this._started&&!this._beingDestroyed&&
n.emit(this.domNode,b.toLowerCase(),a);return c},on:function(b,a){var e=this._onMap(b);return e?h.after(this,e,a,!0):this.own(n(this.domNode,b,a))[0]},_onMap:function(b){var a=this.constructor,e=a._onMap;if(!e){var e=a._onMap={},c;for(c in a.prototype)/^on/.test(c)&&(e[c.replace(/^on/,"").toLowerCase()]=c)}return e["string"==typeof b&&b.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?q.findWidgets(this.containerNode):
[]},getParent:function(){return q.getEnclosingWidget(this.domNode.parentNode)},connect:function(b,a,e){return this.own(f.connect(b,a,this,e))[0]},disconnect:function(b){b.remove()},subscribe:function(b,a){return this.own(t.subscribe(b,r.hitch(this,a)))[0]},unsubscribe:function(b){b.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir.toLowerCase():b.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=s.get(this.domNode,"display")},placeAt:function(b,a){var c=
!b.tagName&&q.byId(b);c&&c.addChild&&(!a||"number"===typeof a)?c.addChild(this,a):(c=c&&"domNode"in c?c.containerNode&&!/after|before|replace/.test(a||"")?c.containerNode:c.domNode:d.byId(b,this.ownerDocument),e.place(this.domNode,c,a),!this._started&&(this.getParent()||{})._started&&this.startup());return this},defer:function(b,a){var e=setTimeout(r.hitch(this,function(){e&&(e=null,this._destroyed||r.hitch(this,b)())}),a||0);return{remove:function(){e&&(clearTimeout(e),e=null);return null}}}});x("dojo-bidi")&&
l.extend(D);return l})},"dijit/_base":function(){define("./main ./a11y ./WidgetSet ./_base/focus ./_base/manager ./_base/place ./_base/popup ./_base/scroll ./_base/sniff ./_base/typematic ./_base/wai ./_base/window".split(" "),function(m){return m._base})},"dojo/touch":function(){define("./_base/kernel ./aspect ./dom ./dom-class ./_base/lang ./on ./has ./mouse ./domReady ./_base/window".split(" "),function(m,k,h,l,f,a,d,g,c,e){function b(b,e,c){return r&&c?function(b,e){return a(b,c,e)}:u?function(c,
d){var g=a(c,e,function(b){d.call(this,b);H=(new Date).getTime()}),f=a(c,b,function(b){(!H||(new Date).getTime()>H+1E3)&&d.call(this,b)});return{remove:function(){g.remove();f.remove()}}}:function(e,c){return a(e,b,c)}}function s(b){do if(void 0!==b.dojoClick)return b;while(b=b.parentNode)}function x(b,c,d){var g=s(b.target);if(t=!b.target.disabled&&g&&g.dojoClick)if(w=(p="useTarget"==t)?g:b.target,p&&b.preventDefault(),D=b.changedTouches?b.changedTouches[0].pageX-e.global.pageXOffset:b.clientX,q=
b.changedTouches?b.changedTouches[0].pageY-e.global.pageYOffset:b.clientY,F=("object"==typeof t?t.x:"number"==typeof t?t:0)||4,E=("object"==typeof t?t.y:"number"==typeof t?t:0)||4,!y){y=!0;var f=function(b){t=p?h.isDescendant(e.doc.elementFromPoint(b.changedTouches?b.changedTouches[0].pageX-e.global.pageXOffset:b.clientX,b.changedTouches?b.changedTouches[0].pageY-e.global.pageYOffset:b.clientY),w):t&&(b.changedTouches?b.changedTouches[0].target:b.target)==w&&Math.abs((b.changedTouches?b.changedTouches[0].pageX-
e.global.pageXOffset:b.clientX)-D)<=F&&Math.abs((b.changedTouches?b.changedTouches[0].pageY-e.global.pageYOffset:b.clientY)-q)<=E};e.doc.addEventListener(c,function(b){f(b);p&&b.preventDefault()},!0);e.doc.addEventListener(d,function(b){f(b);if(t){z=(new Date).getTime();var e=p?w:b.target;"LABEL"===e.tagName&&(e=h.byId(e.getAttribute("for"))||e);var c=b.changedTouches?b.changedTouches[0]:b,d=function(a){var e=document.createEvent("MouseEvents");e._dojo_click=!0;e.initMouseEvent(a,!0,!0,b.view,b.detail,
c.screenX,c.screenY,c.clientX,c.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,null);return e},g=d("mousedown"),s=d("mouseup"),x=d("click");setTimeout(function(){a.emit(e,"mousedown",g);a.emit(e,"mouseup",s);a.emit(e,"click",x);z=(new Date).getTime()},0)}},!0);b=function(b){e.doc.addEventListener(b,function(a){!a._dojo_click&&((new Date).getTime()<=z+1E3&&!("INPUT"==a.target.tagName&&l.contains(a.target,"dijitOffScreen")))&&(a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),
"click"==b&&(("INPUT"!=a.target.tagName||"radio"==a.target.type||"checkbox"==a.target.type)&&"TEXTAREA"!=a.target.tagName&&"AUDIO"!=a.target.tagName&&"VIDEO"!=a.target.tagName)&&a.preventDefault())},!0)};b("click");b("mousedown");b("mouseup")}}var v=5>d("ios"),r=d("pointer-events")||d("MSPointer"),n=function(){var b={},a;for(a in{down:1,move:1,up:1,cancel:1,over:1,out:1})b[a]=d("MSPointer")?"MSPointer"+a.charAt(0).toUpperCase()+a.slice(1):"pointer"+a;return b}(),u=d("touch-events"),y,t,p=!1,w,D,q,
F,E,z,H,I;d("touch")&&(r?c(function(){e.doc.addEventListener(n.down,function(b){x(b,n.move,n.up)},!0)}):c(function(){function b(a){var e=f.delegate(a,{bubbles:!0});6<=d("ios")&&(e.touches=a.touches,e.altKey=a.altKey,e.changedTouches=a.changedTouches,e.ctrlKey=a.ctrlKey,e.metaKey=a.metaKey,e.shiftKey=a.shiftKey,e.targetTouches=a.targetTouches);return e}I=e.body();e.doc.addEventListener("touchstart",function(b){H=(new Date).getTime();var e=I;I=b.target;a.emit(e,"dojotouchout",{relatedTarget:I,bubbles:!0});
a.emit(I,"dojotouchover",{relatedTarget:e,bubbles:!0});x(b,"touchmove","touchend")},!0);a(e.doc,"touchmove",function(c){H=(new Date).getTime();var d=e.doc.elementFromPoint(c.pageX-(v?0:e.global.pageXOffset),c.pageY-(v?0:e.global.pageYOffset));d&&(I!==d&&(a.emit(I,"dojotouchout",{relatedTarget:d,bubbles:!0}),a.emit(d,"dojotouchover",{relatedTarget:I,bubbles:!0}),I=d),a.emit(d,"dojotouchmove",b(c))||c.preventDefault())});a(e.doc,"touchend",function(c){H=(new Date).getTime();var d=e.doc.elementFromPoint(c.pageX-
(v?0:e.global.pageXOffset),c.pageY-(v?0:e.global.pageYOffset))||e.body();a.emit(d,"dojotouchend",b(c))})}));k={press:b("mousedown","touchstart",n.down),move:b("mousemove","dojotouchmove",n.move),release:b("mouseup","dojotouchend",n.up),cancel:b(g.leave,"touchcancel",r?n.cancel:null),over:b("mouseover","dojotouchover",n.over),out:b("mouseout","dojotouchout",n.out),enter:g._eventHandler(b("mouseover","dojotouchover",n.over)),leave:g._eventHandler(b("mouseout","dojotouchout",n.out))};return m.touch=
k})},"dijit/form/_FormValueMixin":function(){define("dojo/_base/declare dojo/dom-attr dojo/keys dojo/_base/lang dojo/on ./_FormWidgetMixin".split(" "),function(m,k,h,l,f,a){return m("dijit.form._FormValueMixin",a,{readOnly:!1,_setReadOnlyAttr:function(a){k.set(this.focusNode,"readOnly",a);this._set("readOnly",a)},postCreate:function(){this.inherited(arguments);void 0===this._resetValue&&(this._lastValueReported=this._resetValue=this.value)},_setValueAttr:function(a,g){this._handleOnChange(a,g)},_handleOnChange:function(a,
g){this._set("value",a);this.inherited(arguments)},undo:function(){this._setValueAttr(this._lastValueReported,!1)},reset:function(){this._hasBeenBlurred=!1;this._setValueAttr(this._resetValue,!0)}})})},"dojo/Stateful":function(){define(["./_base/declare","./_base/lang","./_base/array","./when"],function(m,k,h,l){return m("dojo.Stateful",null,{_attrPairNames:{},_getAttrNames:function(f){var a=this._attrPairNames;return a[f]?a[f]:a[f]={s:"_"+f+"Setter",g:"_"+f+"Getter"}},postscript:function(f){f&&this.set(f)},
_get:function(f,a){return"function"===typeof this[a.g]?this[a.g]():this[f]},get:function(f){return this._get(f,this._getAttrNames(f))},set:function(f,a){if("object"===typeof f){for(var d in f)f.hasOwnProperty(d)&&"_watchCallbacks"!=d&&this.set(d,f[d]);return this}d=this._getAttrNames(f);var g=this._get(f,d);d=this[d.s];var c;"function"===typeof d?c=d.apply(this,Array.prototype.slice.call(arguments,1)):this[f]=a;if(this._watchCallbacks){var e=this;l(c,function(){e._watchCallbacks(f,g,a)})}return this},
_changeAttrValue:function(f,a){var d=this.get(f);this[f]=a;this._watchCallbacks&&this._watchCallbacks(f,d,a);return this},watch:function(f,a){var d=this._watchCallbacks;if(!d)var g=this,d=this._watchCallbacks=function(b,a,e,c){var f=function(c){if(c){c=c.slice();for(var d=0,f=c.length;d<f;d++)c[d].call(g,b,a,e)}};f(d["_"+b]);c||f(d["*"])};!a&&"function"===typeof f?(a=f,f="*"):f="_"+f;var c=d[f];"object"!==typeof c&&(c=d[f]=[]);c.push(a);var e={};e.unwatch=e.remove=function(){var b=h.indexOf(c,a);
-1<b&&c.splice(b,1)};return e}})})},"dijit/_CssStateMixin":function(){define("dojo/_base/array dojo/_base/declare dojo/dom dojo/dom-class dojo/has dojo/_base/lang dojo/on dojo/domReady dojo/touch dojo/_base/window ./a11yclick ./registry".split(" "),function(m,k,h,l,f,a,d,g,c,e,b,s){k=k("dijit._CssStateMixin",[],{hovering:!1,active:!1,_applyAttributes:function(){this.inherited(arguments);m.forEach("disabled readOnly checked selected focused state hovering active _opened".split(" "),function(b){this.watch(b,
a.hitch(this,"_setStateClass"))},this);for(var b in this.cssStateNodes||{})this._trackMouseState(this[b],this.cssStateNodes[b]);this._trackMouseState(this.domNode,this.baseClass);this._setStateClass()},_cssMouseEvent:function(b){if(!this.disabled)switch(b.type){case "mouseover":case "MSPointerOver":case "pointerover":this._set("hovering",!0);this._set("active",this._mouseDown);break;case "mouseout":case "MSPointerOut":case "pointerout":this._set("hovering",!1);this._set("active",!1);break;case "mousedown":case "touchstart":case "MSPointerDown":case "pointerdown":case "keydown":this._set("active",
!0);break;case "mouseup":case "dojotouchend":case "MSPointerUp":case "pointerup":case "keyup":this._set("active",!1)}},_setStateClass:function(){function b(e){a=a.concat(m.map(a,function(b){return b+e}),"dijit"+e)}var a=this.baseClass.split(" ");this.isLeftToRight()||b("Rtl");var e="mixed"==this.checked?"Mixed":this.checked?"Checked":"";this.checked&&b(e);this.state&&b(this.state);this.selected&&b("Selected");this._opened&&b("Opened");this.disabled?b("Disabled"):this.readOnly?b("ReadOnly"):this.active?
b("Active"):this.hovering&&b("Hover");this.focused&&b("Focused");var e=this.stateNode||this.domNode,c={};m.forEach(e.className.split(" "),function(b){c[b]=!0});"_stateClasses"in this&&m.forEach(this._stateClasses,function(b){delete c[b]});m.forEach(a,function(b){c[b]=!0});var d=[],g;for(g in c)d.push(g);e.className=d.join(" ");this._stateClasses=a},_subnodeCssMouseEvent:function(b,a,e){function c(e){l.toggle(b,a+"Active",e)}if(!this.disabled&&!this.readOnly)switch(e.type){case "mouseover":case "MSPointerOver":case "pointerover":l.toggle(b,
a+"Hover",!0);break;case "mouseout":case "MSPointerOut":case "pointerout":l.toggle(b,a+"Hover",!1);c(!1);break;case "mousedown":case "touchstart":case "MSPointerDown":case "pointerdown":case "keydown":c(!0);break;case "mouseup":case "MSPointerUp":case "pointerup":case "dojotouchend":case "keyup":c(!1);break;case "focus":case "focusin":l.toggle(b,a+"Focused",!0);break;case "blur":case "focusout":l.toggle(b,a+"Focused",!1)}},_trackMouseState:function(b,a){b._cssState=a}});g(function(){function a(b,
e,c){if(!c||!h.isDescendant(c,e))for(;e&&e!=c;e=e.parentNode)if(e._cssState){var d=s.getEnclosingWidget(e);d&&(e==d.domNode?d._cssMouseEvent(b):d._subnodeCssMouseEvent(e,e._cssState,b))}}var g=e.body(),f;d(g,c.over,function(b){a(b,b.target,b.relatedTarget)});d(g,c.out,function(b){a(b,b.target,b.relatedTarget)});d(g,b.press,function(b){f=b.target;a(b,f)});d(g,b.release,function(b){a(b,f);f=null});d(g,"focusin, focusout",function(b){var a=b.target;if(a._cssState&&!a.getAttribute("widgetId")){var e=
s.getEnclosingWidget(a);e&&e._subnodeCssMouseEvent(a,a._cssState,b)}})});return k})},"dijit/_base/manager":function(){define(["dojo/_base/array","dojo/_base/config","dojo/_base/lang","../registry","../main"],function(m,k,h,l,f){var a={};m.forEach("byId getUniqueId findWidgets _destroyAll byNode getEnclosingWidget".split(" "),function(d){a[d]=l[d]});h.mixin(a,{defaultDuration:k.defaultDuration||200});h.mixin(f,a);return f})},"dijit/_base/sniff":function(){define(["dojo/uacss"],function(){})},"dijit/BackgroundIframe":function(){define("require ./main dojo/_base/config dojo/dom-construct dojo/dom-style dojo/_base/lang dojo/on dojo/sniff".split(" "),
function(m,k,h,l,f,a,d,g){g.add("config-bgIframe",g("ie")&&!/IEMobile\/10\.0/.test(navigator.userAgent)||g("trident")&&/Windows NT 6.[01]/.test(navigator.userAgent));var c=new function(){var a=[];this.pop=function(){var b;a.length?(b=a.pop(),b.style.display=""):(9>g("ie")?(b="\x3ciframe src\x3d'"+(h.dojoBlankHtmlUrl||m.toUrl("dojo/resources/blank.html")||'javascript:""')+"' role\x3d'presentation' style\x3d'position: absolute; left: 0px; top: 0px;z-index: -1; filter:Alpha(Opacity\x3d\"0\");'\x3e",
b=document.createElement(b)):(b=l.create("iframe"),b.src='javascript:""',b.className="dijitBackgroundIframe",b.setAttribute("role","presentation"),f.set(b,"opacity",0.1)),b.tabIndex=-1);return b};this.push=function(b){b.style.display="none";a.push(b)}};k.BackgroundIframe=function(e){if(!e.id)throw Error("no id");if(g("config-bgIframe")){var b=this.iframe=c.pop();e.appendChild(b);7>g("ie")||g("quirks")?(this.resize(e),this._conn=d(e,"resize",a.hitch(this,"resize",e))):f.set(b,{width:"100%",height:"100%"})}};
a.extend(k.BackgroundIframe,{resize:function(a){this.iframe&&f.set(this.iframe,{width:a.offsetWidth+"px",height:a.offsetHeight+"px"})},destroy:function(){this._conn&&(this._conn.remove(),this._conn=null);this.iframe&&(this.iframe.parentNode.removeChild(this.iframe),c.push(this.iframe),delete this.iframe)}});return k.BackgroundIframe})},"dijit/typematic":function(){define("dojo/_base/array dojo/_base/connect dojo/_base/lang dojo/on dojo/sniff ./main".split(" "),function(m,k,h,l,f,a){var d=a.typematic=
{_fireEventAndReload:function(){this._timer=null;this._callback(++this._count,this._node,this._evt);this._currentTimeout=Math.max(0>this._currentTimeout?this._initialDelay:1<this._subsequentDelay?this._subsequentDelay:Math.round(this._currentTimeout*this._subsequentDelay),this._minDelay);this._timer=setTimeout(h.hitch(this,"_fireEventAndReload"),this._currentTimeout)},trigger:function(a,c,e,b,d,f,k,l){if(d!=this._obj){this.stop();this._initialDelay=k||500;this._subsequentDelay=f||0.9;this._minDelay=
l||10;this._obj=d;this._node=e;this._count=this._currentTimeout=-1;this._callback=h.hitch(c,b);this._evt={faux:!0};for(var m in a)"layerX"!=m&&"layerY"!=m&&(c=a[m],"function"!=typeof c&&"undefined"!=typeof c&&(this._evt[m]=c));this._fireEventAndReload()}},stop:function(){this._timer&&(clearTimeout(this._timer),this._timer=null);this._obj&&(this._callback(-1,this._node,this._evt),this._obj=null)},addKeyListener:function(a,c,e,b,f,x,v){var r="keyCode"in c?"keyCode":"charCode"in c?"charCode":"charOrCode",
n=[l(a,"keyCode"in c?"keydown":"charCode"in c?"keypress":k._keypress,h.hitch(this,function(h){h[r]==c[r]&&(void 0===c.ctrlKey||c.ctrlKey==h.ctrlKey)&&(void 0===c.altKey||c.altKey==h.altKey)&&(void 0===c.metaKey||c.metaKey==(h.metaKey||!1))&&(void 0===c.shiftKey||c.shiftKey==h.shiftKey)?(h.stopPropagation(),h.preventDefault(),d.trigger(h,e,a,b,c,f,x,v)):d._obj==c&&d.stop()})),l(a,"keyup",h.hitch(this,function(){d._obj==c&&d.stop()}))];return{remove:function(){m.forEach(n,function(b){b.remove()})}}},
addMouseListener:function(a,c,e,b,s,x){var k=[l(a,"mousedown",h.hitch(this,function(f){f.preventDefault();d.trigger(f,c,a,e,a,b,s,x)})),l(a,"mouseup",h.hitch(this,function(b){this._obj&&b.preventDefault();d.stop()})),l(a,"mouseout",h.hitch(this,function(b){this._obj&&b.preventDefault();d.stop()})),l(a,"dblclick",h.hitch(this,function(k){k.preventDefault();9>f("ie")&&(d.trigger(k,c,a,e,a,b,s,x),setTimeout(h.hitch(this,d.stop),50))}))];return{remove:function(){m.forEach(k,function(b){b.remove()})}}},
addListener:function(a,c,e,b,d,f,h,k){var l=[this.addKeyListener(c,e,b,d,f,h,k),this.addMouseListener(a,b,d,f,h,k)];return{remove:function(){m.forEach(l,function(b){b.remove()})}}}};return d})},"dojo/_base/url":function(){define(["./kernel"],function(m){var k=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,h=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/,l=function(){for(var f=arguments,a=[f[0]],d=1;d<f.length;d++)if(f[d]){var g=new l(f[d]+""),a=new l(a[0]+"");if(""==
g.path&&!g.scheme&&!g.authority&&!g.query)null!=g.fragment&&(a.fragment=g.fragment),g=a;else if(!g.scheme&&(g.scheme=a.scheme,!g.authority&&(g.authority=a.authority,"/"!=g.path.charAt(0)))){for(var a=(a.path.substring(0,a.path.lastIndexOf("/")+1)+g.path).split("/"),c=0;c<a.length;c++)"."==a[c]?c==a.length-1?a[c]="":(a.splice(c,1),c--):0<c&&(!(1==c&&""==a[0])&&".."==a[c]&&".."!=a[c-1])&&(c==a.length-1?(a.splice(c,1),a[c-1]=""):(a.splice(c-1,2),c-=2));g.path=a.join("/")}a=[];g.scheme&&a.push(g.scheme,
":");g.authority&&a.push("//",g.authority);a.push(g.path);g.query&&a.push("?",g.query);g.fragment&&a.push("#",g.fragment)}this.uri=a.join("");f=this.uri.match(k);this.scheme=f[2]||(f[1]?"":null);this.authority=f[4]||(f[3]?"":null);this.path=f[5];this.query=f[7]||(f[6]?"":null);this.fragment=f[9]||(f[8]?"":null);null!=this.authority&&(f=this.authority.match(h),this.user=f[3]||null,this.password=f[4]||null,this.host=f[6]||f[7],this.port=f[9]||null)};l.prototype.toString=function(){return this.uri};
return m._Url=l})},"dojo/date/stamp":function(){define(["../_base/lang","../_base/array"],function(m,k){var h={};m.setObject("dojo.date.stamp",h);h.fromISOString=function(l,f){h._isoRegExp||(h._isoRegExp=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/);var a=h._isoRegExp.exec(l),d=null;if(a){a.shift();a[1]&&a[1]--;a[6]&&(a[6]*=1E3);f&&(f=new Date(f),k.forEach(k.map("FullYear Month Date Hours Minutes Seconds Milliseconds".split(" "),function(a){return f["get"+
a]()}),function(e,b){a[b]=a[b]||e}));d=new Date(a[0]||1970,a[1]||0,a[2]||1,a[3]||0,a[4]||0,a[5]||0,a[6]||0);100>a[0]&&d.setFullYear(a[0]||1970);var g=0,c=a[7]&&a[7].charAt(0);"Z"!=c&&(g=60*(a[8]||0)+(Number(a[9])||0),"-"!=c&&(g*=-1));c&&(g-=d.getTimezoneOffset());g&&d.setTime(d.getTime()+6E4*g)}return d};h.toISOString=function(h,f){var a=function(b){return 10>b?"0"+b:b};f=f||{};var d=[],g=f.zulu?"getUTC":"get",c="";"time"!=f.selector&&(c=h[g+"FullYear"](),c=["0000".substr((c+"").length)+c,a(h[g+"Month"]()+
1),a(h[g+"Date"]())].join("-"));d.push(c);if("date"!=f.selector){c=[a(h[g+"Hours"]()),a(h[g+"Minutes"]()),a(h[g+"Seconds"]())].join(":");g=h[g+"Milliseconds"]();f.milliseconds&&(c+="."+(100>g?"0":"")+a(g));if(f.zulu)c+="Z";else if("time"!=f.selector)var g=h.getTimezoneOffset(),e=Math.abs(g),c=c+((0<g?"-":"+")+a(Math.floor(e/60))+":"+a(e%60));d.push(c)}return d.join("T")};return h})},"dojo/text":function(){define(["./_base/kernel","require","./has","./request"],function(m,k,h,l){var f;f=function(a,
b,c){l(a,{sync:!!b,headers:{"X-Requested-With":null}}).then(c)};var a={},d=function(a){if(a){a=a.replace(/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,"");var b=a.match(/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im);b&&(a=b[1])}else a="";return a},g={},c={};m.cache=function(e,b,c){var g;"string"==typeof e?/\//.test(e)?(g=e,c=b):g=k.toUrl(e.replace(/\./g,"/")+(b?"/"+b:"")):(g=e+"",c=b);e=void 0!=c&&"string"!=typeof c?c.value:c;c=c&&c.sanitize;if("string"==typeof e)return a[g]=e,c?d(e):e;if(null===
e)return delete a[g],null;g in a||f(g,!0,function(b){a[g]=b});return c?d(a[g]):a[g]};return{dynamic:!0,normalize:function(a,b){var c=a.split("!"),d=c[0];return(/^\./.test(d)?b(d):d)+(c[1]?"!"+c[1]:"")},load:function(e,b,h){e=e.split("!");var x=1<e.length,k=e[0],l=b.toUrl(e[0]);e="url:"+l;var m=g,u=function(b){h(x?d(b):b)};k in a?m=a[k]:b.cache&&e in b.cache?m=b.cache[e]:l in a&&(m=a[l]);if(m===g)if(c[l])c[l].push(u);else{var y=c[l]=[u];f(l,!b.async,function(b){a[k]=a[l]=b;for(var e=0;e<y.length;)y[e++](b);
delete c[l]})}else u(m)}}})},"dijit/_base/place":function(){define(["dojo/_base/array","dojo/_base/lang","dojo/window","../place","../main"],function(m,k,h,l,f){var a={getViewport:function(){return h.getBox()}};a.placeOnScreen=l.at;a.placeOnScreenAroundElement=function(a,g,c,e){var b;if(k.isArray(c))b=c;else{b=[];for(var f in c)b.push({aroundCorner:f,corner:c[f]})}return l.around(a,g,b,!0,e)};a.placeOnScreenAroundNode=a.placeOnScreenAroundElement;a.placeOnScreenAroundRectangle=a.placeOnScreenAroundElement;
a.getPopupAroundAlignment=function(a,g){var c={};m.forEach(a,function(a){var b=g;switch(a){case "after":c[g?"BR":"BL"]=g?"BL":"BR";break;case "before":c[g?"BL":"BR"]=g?"BR":"BL";break;case "below-alt":b=!b;case "below":c[b?"BL":"BR"]=b?"TL":"TR";c[b?"BR":"BL"]=b?"TR":"TL";break;case "above-alt":b=!b;default:c[b?"TL":"TR"]=b?"BL":"BR",c[b?"TR":"TL"]=b?"BR":"BL"}});return c};k.mixin(f,a);return f})},"dijit/registry":function(){define(["dojo/_base/array","dojo/_base/window","./main"],function(m,k,h){var l=
{},f={},a={length:0,add:function(a){if(f[a.id])throw Error("Tried to register widget with id\x3d\x3d"+a.id+" but that id is already registered");f[a.id]=a;this.length++},remove:function(a){f[a]&&(delete f[a],this.length--)},byId:function(a){return"string"==typeof a?f[a]:a},byNode:function(a){return f[a.getAttribute("widgetId")]},toArray:function(){var a=[],g;for(g in f)a.push(f[g]);return a},getUniqueId:function(a){var g;do g=a+"_"+(a in l?++l[a]:l[a]=0);while(f[g]);return"dijit"==h._scopeName?g:
h._scopeName+"_"+g},findWidgets:function(a,g){function c(b){for(b=b.firstChild;b;b=b.nextSibling)if(1==b.nodeType){var a=b.getAttribute("widgetId");a?(a=f[a])&&e.push(a):b!==g&&c(b)}}var e=[];c(a);return e},_destroyAll:function(){h._curFocus=null;h._prevFocus=null;h._activeStack=[];m.forEach(a.findWidgets(k.body()),function(a){a._destroyed||(a.destroyRecursive?a.destroyRecursive():a.destroy&&a.destroy())})},getEnclosingWidget:function(a){for(;a;){var g=1==a.nodeType&&a.getAttribute("widgetId");if(g)return f[g];
a=a.parentNode}return null},_hash:f};return h.registry=a})},"dijit/form/_FormWidgetMixin":function(){define("dojo/_base/array dojo/_base/declare dojo/dom-attr dojo/dom-style dojo/_base/lang dojo/mouse dojo/on dojo/sniff dojo/window ../a11y".split(" "),function(m,k,h,l,f,a,d,g,c,e){return k("dijit.form._FormWidgetMixin",null,{name:"",alt:"",value:"",type:"text","aria-label":"focusNode",tabIndex:"0",_setTabIndexAttr:"focusNode",disabled:!1,intermediateChanges:!1,scrollOnFocus:!0,_setIdAttr:"focusNode",
_setDisabledAttr:function(b){this._set("disabled",b);h.set(this.focusNode,"disabled",b);this.valueNode&&h.set(this.valueNode,"disabled",b);this.focusNode.setAttribute("aria-disabled",b?"true":"false");b?(this._set("hovering",!1),this._set("active",!1),b="tabIndex"in this.attributeMap?this.attributeMap.tabIndex:"_setTabIndexAttr"in this?this._setTabIndexAttr:"focusNode",m.forEach(f.isArray(b)?b:[b],function(b){b=this[b];g("webkit")||e.hasDefaultTabStop(b)?b.setAttribute("tabIndex","-1"):b.removeAttribute("tabIndex")},
this)):""!=this.tabIndex&&this.set("tabIndex",this.tabIndex)},_onFocus:function(b){"mouse"==b&&this.isFocusable()&&(this.__mouseUpHandle&&this.__mouseUpHandle.remove(),this.__focusHandle&&this.__focusHandle.remove(),delete this.__mouseUpHandle,delete this.__focusHandle,this.__focusHandle=this.own(d(this.focusNode,"focus",f.hitch(function(){this.__mouseUpHandle&&this.__mouseUpHandle.remove();this.__focusHandle&&this.__focusHandle.remove();delete this.__mouseUpHandle;delete this.__focusHandle})))[0],
this.__mouseUpHandle=this.own(d(this.ownerDocumentBody,"mouseup, touchend",f.hitch(this,function(b){this.__mouseUpHandle&&this.__mouseUpHandle.remove();this.__focusHandle&&this.__focusHandle.remove();delete this.__mouseUpHandle;delete this.__focusHandle;this.focused&&("touchend"==b.type?this.defer("focus"):this.focus())})))[0]);this.scrollOnFocus&&this.defer(function(){c.scrollIntoView(this.domNode)});this.inherited(arguments)},isFocusable:function(){return!this.disabled&&this.focusNode&&"none"!=
l.get(this.domNode,"display")},focus:function(){if(!this.disabled&&this.focusNode.focus)try{this.focusNode.focus()}catch(b){}},compare:function(b,a){return"number"==typeof b&&"number"==typeof a?isNaN(b)&&isNaN(a)?0:b-a:b>a?1:b<a?-1:0},onChange:function(){},_onChangeActive:!1,_handleOnChange:function(b,a){if(void 0==this._lastValueReported&&(null===a||!this._onChangeActive))this._resetValue=this._lastValueReported=b;this._pendingOnChange=this._pendingOnChange||typeof b!=typeof this._lastValueReported||
0!=this.compare(b,this._lastValueReported);if((this.intermediateChanges||a||void 0===a)&&this._pendingOnChange)this._lastValueReported=b,this._pendingOnChange=!1,this._onChangeActive&&(this._onChangeHandle&&this._onChangeHandle.remove(),this._onChangeHandle=this.defer(function(){this._onChangeHandle=null;this.onChange(b)}))},create:function(){this.inherited(arguments);this._onChangeActive=!0},destroy:function(){this.__mouseUpHandle&&this.__mouseUpHandle.remove();this.__focusHandle&&this.__focusHandle.remove();
delete this.__mouseUpHandle;delete this.__focusHandle;this._onChangeHandle&&(this._onChangeHandle.remove(),this.onChange(this._lastValueReported));this.inherited(arguments)}})})},"dijit/_AttachMixin":function(){define("require dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/mouse dojo/on dojo/touch ./_WidgetBase".split(" "),function(m,k,h,l,f,a,d,g,c){var e=f.delegate(g,{mouseenter:a.enter,mouseleave:a.leave,keypress:h._keypress}),b;h=l("dijit._AttachMixin",null,{constructor:function(){this._attachPoints=
[];this._attachEvents=[]},buildRendering:function(){this.inherited(arguments);this._attachTemplateNodes(this.domNode);this._beforeFillContent()},_beforeFillContent:function(){},_attachTemplateNodes:function(b){for(var a=b;;)if(1==a.nodeType&&(this._processTemplateNode(a,function(b,a){return b.getAttribute(a)},this._attach)||this.searchContainerNode)&&a.firstChild)a=a.firstChild;else{if(a==b)break;for(;!a.nextSibling;)if(a=a.parentNode,a==b)return;a=a.nextSibling}},_processTemplateNode:function(b,
a,c){var e=!0,g=this.attachScope||this,d=a(b,"dojoAttachPoint")||a(b,"data-dojo-attach-point");if(d)for(var h=d.split(/\s*,\s*/);d=h.shift();)f.isArray(g[d])?g[d].push(b):g[d]=b,e="containerNode"!=d,this._attachPoints.push(d);if(a=a(b,"dojoAttachEvent")||a(b,"data-dojo-attach-event")){d=a.split(/\s*,\s*/);for(h=f.trim;a=d.shift();)if(a){var k=null;-1!=a.indexOf(":")?(k=a.split(":"),a=h(k[0]),k=h(k[1])):a=h(a);k||(k=a);this._attachEvents.push(c(b,a,f.hitch(g,k)))}}return e},_attach:function(a,c,g){c=
c.replace(/^on/,"").toLowerCase();c="dijitclick"==c?b||(b=m("./a11yclick")):e[c]||c;return d(a,c,g)},_detachTemplateNodes:function(){var b=this.attachScope||this;k.forEach(this._attachPoints,function(a){delete b[a]});this._attachPoints=[];k.forEach(this._attachEvents,function(b){b.remove()});this._attachEvents=[]},destroyRendering:function(){this._detachTemplateNodes();this.inherited(arguments)}});f.extend(c,{dojoAttachEvent:"",dojoAttachPoint:""});return h})},"dojo/uacss":function(){define(["./dom-geometry",
"./_base/lang","./domReady","./sniff","./_base/window"],function(m,k,h,l,f){var a=f.doc.documentElement;f=l("ie");var d=l("opera"),g=Math.floor,c=l("ff"),e=!l("ie")&&l("trident"),b=m.boxModel.replace(/-/,""),d={dj_quirks:l("quirks"),dj_opera:d,dj_khtml:l("khtml"),dj_webkit:l("webkit"),dj_safari:l("safari"),dj_chrome:l("chrome"),dj_gecko:l("mozilla"),dj_ios:l("ios"),dj_android:l("android"),dj_trident:e};f&&(d.dj_ie=!0,d["dj_ie"+g(f)]=!0,d.dj_iequirks=l("quirks"));c&&(d["dj_ff"+g(c)]=!0);e&&(d["dj_trident"+
g(e)]=!0);d["dj_"+b]=!0;var s="",x;for(x in d)d[x]&&(s+=x+" ");a.className=k.trim(a.className+" "+s);h(function(){if(!m.isBodyLtr()){var b="dj_rtl dijitRtl "+s.replace(/ /g,"-rtl ");a.className=k.trim(a.className+" "+b+"dj_rtl dijitRtl "+s.replace(/ /g,"-rtl "))}});return l})},"dijit/place":function(){define("dojo/_base/array dojo/dom-geometry dojo/dom-style dojo/_base/kernel dojo/_base/window ./Viewport ./main".split(" "),function(m,k,h,l,f,a,d){function g(c,b,g,d){var l=a.getEffectiveBox(c.ownerDocument);
(!c.parentNode||"body"!=String(c.parentNode.tagName).toLowerCase())&&f.body(c.ownerDocument).appendChild(c);var r=null;m.some(b,function(b){var a=b.corner,f=b.pos,h=0,m={w:{L:l.l+l.w-f.x,R:f.x-l.l,M:l.w}[a.charAt(1)],h:{T:l.t+l.h-f.y,B:f.y-l.t,M:l.h}[a.charAt(0)]},q=c.style;q.left=q.right="auto";g&&(h=g(c,b.aroundCorner,a,m,d),h="undefined"==typeof h?0:h);var n=c.style,E=n.display,z=n.visibility;"none"==n.display&&(n.visibility="hidden",n.display="");q=k.position(c);n.display=E;n.visibility=z;E={L:f.x,
R:f.x-q.w,M:Math.max(l.l,Math.min(l.l+l.w,f.x+(q.w>>1))-q.w)}[a.charAt(1)];z={T:f.y,B:f.y-q.h,M:Math.max(l.t,Math.min(l.t+l.h,f.y+(q.h>>1))-q.h)}[a.charAt(0)];f=Math.max(l.l,E);n=Math.max(l.t,z);E=Math.min(l.l+l.w,E+q.w);z=Math.min(l.t+l.h,z+q.h);E-=f;z-=n;h+=q.w-E+(q.h-z);if(null==r||h<r.overflow)r={corner:a,aroundCorner:b.aroundCorner,x:f,y:n,w:E,h:z,overflow:h,spaceAvailable:m};return!h});r.overflow&&g&&g(c,r.aroundCorner,r.corner,r.spaceAvailable,d);b=r.y;var n=r.x,u=f.body(c.ownerDocument);/relative|absolute/.test(h.get(u,
"position"))&&(b-=h.get(u,"marginTop"),n-=h.get(u,"marginLeft"));u=c.style;u.top=b+"px";u.left=n+"px";u.right="auto";return r}var c={TL:"BR",TR:"BL",BL:"TR",BR:"TL"};return d.place={at:function(a,b,d,f,h){d=m.map(d,function(a){var e={corner:a,aroundCorner:c[a],pos:{x:b.x,y:b.y}};f&&(e.pos.x+="L"==a.charAt(1)?f.x:-f.x,e.pos.y+="T"==a.charAt(0)?f.y:-f.y);return e});return g(a,d,h)},around:function(a,b,c,d,f){function r(b,a){z.push({aroundCorner:b,corner:a,pos:{x:{L:D,R:D+F,M:D+(F>>1)}[b.charAt(1)],
y:{T:q,B:q+E,M:q+(E>>1)}[b.charAt(0)]}})}var n;if("string"==typeof b||"offsetWidth"in b||"ownerSVGElement"in b){if(n=k.position(b,!0),/^(above|below)/.test(c[0])){var u=k.getBorderExtents(b),y=b.firstChild?k.getBorderExtents(b.firstChild):{t:0,l:0,b:0,r:0},t=k.getBorderExtents(a),p=a.firstChild?k.getBorderExtents(a.firstChild):{t:0,l:0,b:0,r:0};n.y+=Math.min(u.t+y.t,t.t+p.t);n.h-=Math.min(u.t+y.t,t.t+p.t)+Math.min(u.b+y.b,t.b+p.b)}}else n=b;if(b.parentNode){u="absolute"==h.getComputedStyle(b).position;
for(b=b.parentNode;b&&1==b.nodeType&&"BODY"!=b.nodeName;){y=k.position(b,!0);t=h.getComputedStyle(b);/relative|absolute/.test(t.position)&&(u=!1);if(!u&&/hidden|auto|scroll/.test(t.overflow)){var p=Math.min(n.y+n.h,y.y+y.h),w=Math.min(n.x+n.w,y.x+y.w);n.x=Math.max(n.x,y.x);n.y=Math.max(n.y,y.y);n.h=p-n.y;n.w=w-n.x}"absolute"==t.position&&(u=!0);b=b.parentNode}}var D=n.x,q=n.y,F="w"in n?n.w:n.w=n.width,E="h"in n?n.h:(l.deprecated("place.around: dijit/place.__Rectangle: { x:"+D+", y:"+q+", height:"+
n.height+", width:"+F+" } has been deprecated.  Please use { x:"+D+", y:"+q+", h:"+n.height+", w:"+F+" }","","2.0"),n.h=n.height),z=[];m.forEach(c,function(b){var a=d;switch(b){case "above-centered":r("TM","BM");break;case "below-centered":r("BM","TM");break;case "after-centered":a=!a;case "before-centered":r(a?"ML":"MR",a?"MR":"ML");break;case "after":a=!a;case "before":r(a?"TL":"TR",a?"TR":"TL");r(a?"BL":"BR",a?"BR":"BL");break;case "below-alt":a=!a;case "below":r(a?"BL":"BR",a?"TL":"TR");r(a?"BR":
"BL",a?"TR":"TL");break;case "above-alt":a=!a;case "above":r(a?"TL":"TR",a?"BL":"BR");r(a?"TR":"TL",a?"BR":"BL");break;default:r(b.aroundCorner,b.corner)}});a=g(a,z,f,{w:F,h:E});a.aroundNodePos=n;return a}}})},"dojo/promise/all":function(){define(["../_base/array","../Deferred","../when"],function(m,k,h){var l=m.some;return function(f){var a,d;f instanceof Array?d=f:f&&"object"===typeof f&&(a=f);var g,c=[];if(a){d=[];for(var e in a)Object.hasOwnProperty.call(a,e)&&(c.push(e),d.push(a[e]));g={}}else d&&
(g=[]);if(!d||!d.length)return(new k).resolve(g);var b=new k;b.promise.always(function(){g=c=null});var s=d.length;l(d,function(e,d){a||c.push(d);h(e,function(a){b.isFulfilled()||(g[c[d]]=a,0===--s&&b.resolve(g))},b.reject);return b.isFulfilled()});return b.promise}})},"dojo/window":function(){define("./_base/lang ./sniff ./_base/window ./dom ./dom-geometry ./dom-style ./dom-construct".split(" "),function(m,k,h,l,f,a,d){k.add("rtl-adjust-position-for-verticalScrollBar",function(a,e){var b=h.body(e),
g=d.create("div",{style:{overflow:"scroll",overflowX:"visible",direction:"rtl",visibility:"hidden",position:"absolute",left:"0",top:"0",width:"64px",height:"64px"}},b,"last"),k=d.create("div",{style:{overflow:"hidden",direction:"ltr"}},g,"last"),l=0!=f.position(k).x;g.removeChild(k);b.removeChild(g);return l});k.add("position-fixed-support",function(a,e){var b=h.body(e),g=d.create("span",{style:{visibility:"hidden",position:"fixed",left:"1px",top:"1px"}},b,"last"),k=d.create("span",{style:{position:"fixed",
left:"0",top:"0"}},g,"last"),l=f.position(k).x!=f.position(g).x;g.removeChild(k);b.removeChild(g);return l});var g={getBox:function(a){a=a||h.doc;var e="BackCompat"==a.compatMode?h.body(a):a.documentElement,b=f.docScroll(a);if(k("touch")){var d=g.get(a);a=d.innerWidth||e.clientWidth;e=d.innerHeight||e.clientHeight}else a=e.clientWidth,e=e.clientHeight;return{l:b.x,t:b.y,w:a,h:e}},get:function(a){if(k("ie")&&g!==document.parentWindow){a.parentWindow.execScript("document._parentWindow \x3d window;",
"Javascript");var e=a._parentWindow;a._parentWindow=null;return e}return a.parentWindow||a.defaultView},scrollIntoView:function(c,e){try{c=l.byId(c);var b=c.ownerDocument||h.doc,d=h.body(b),g=b.documentElement||d.parentNode,m=k("ie"),r=k("webkit");if(!(c==d||c==g))if(!k("mozilla")&&(!m&&!r&&!k("opera")&&!k("trident"))&&"scrollIntoView"in c)c.scrollIntoView(!1);else{var n="BackCompat"==b.compatMode,u=Math.min(d.clientWidth||g.clientWidth,g.clientWidth||d.clientWidth),y=Math.min(d.clientHeight||g.clientHeight,
g.clientHeight||d.clientHeight),b=r||n?d:g,t=e||f.position(c),p=c.parentNode,r=function(b){return 6>=m||7==m&&n?!1:k("position-fixed-support")&&"fixed"==a.get(b,"position").toLowerCase()},w=this,D=function(a,b,c){"BODY"==a.tagName||"HTML"==a.tagName?w.get(a.ownerDocument).scrollBy(b,c):(b&&(a.scrollLeft+=b),c&&(a.scrollTop+=c))};if(!r(c))for(;p;){p==d&&(p=b);var q=f.position(p),F=r(p),E="rtl"==a.getComputedStyle(p).direction.toLowerCase();if(p==b){q.w=u;q.h=y;if(b==g&&(m||k("trident"))&&E)q.x+=b.offsetWidth-
q.w;if(0>q.x||!m||9<=m||k("trident"))q.x=0;if(0>q.y||!m||9<=m||k("trident"))q.y=0}else{var z=f.getPadBorderExtents(p);q.w-=z.w;q.h-=z.h;q.x+=z.l;q.y+=z.t;var H=p.clientWidth,I=q.w-H;0<H&&0<I&&(E&&k("rtl-adjust-position-for-verticalScrollBar")&&(q.x+=I),q.w=H);H=p.clientHeight;I=q.h-H;0<H&&0<I&&(q.h=H)}F&&(0>q.y&&(q.h+=q.y,q.y=0),0>q.x&&(q.w+=q.x,q.x=0),q.y+q.h>y&&(q.h=y-q.y),q.x+q.w>u&&(q.w=u-q.x));var M=t.x-q.x,O=t.y-q.y,S=M+t.w-q.w,T=O+t.h-q.h,J,A;if(0<S*M&&(p.scrollLeft||p==b||p.scrollWidth>p.offsetHeight)){J=
Math[0>M?"max":"min"](M,S);if(E&&(8==m&&!n||9<=m||k("trident")))J=-J;A=p.scrollLeft;D(p,J,0);J=p.scrollLeft-A;t.x-=J}if(0<T*O&&(p.scrollTop||p==b||p.scrollHeight>p.offsetHeight))J=Math.ceil(Math[0>O?"max":"min"](O,T)),A=p.scrollTop,D(p,0,J),J=p.scrollTop-A,t.y-=J;p=p!=b&&!F&&p.parentNode}}}catch(B){console.error("scrollIntoView: "+B),c.scrollIntoView(!1)}}};m.setObject("dojo.window",g);return g})},"dijit/form/_FormValueWidget":function(){define(["dojo/_base/declare","dojo/sniff","./_FormWidget","./_FormValueMixin"],
function(m,k,h,l){return m("dijit.form._FormValueWidget",[h,l],{_layoutHackIE7:function(){if(7==k("ie"))for(var f=this.domNode,a=f.parentNode,d=f.firstChild||f,g=d.style.filter,c=this;a&&0==a.clientHeight;)(function(){var e=c.connect(a,"onscroll",function(){c.disconnect(e);d.style.filter=(new Date).getMilliseconds();c.defer(function(){d.style.filter=g})})})(),a=a.parentNode}})})},"dijit/_OnDijitClickMixin":function(){define("dojo/on dojo/_base/array dojo/keys dojo/_base/declare dojo/has ./a11yclick".split(" "),
function(m,k,h,l,f,a){m=l("dijit._OnDijitClickMixin",null,{connect:function(d,g,c){return this.inherited(arguments,[d,"ondijitclick"==g?a:g,c])}});m.a11yclick=a;return m})},"dijit/a11yclick":function(){define(["dojo/keys","dojo/mouse","dojo/on","dojo/touch"],function(m,k,h,l){function f(a){if((a.keyCode===m.ENTER||a.keyCode===m.SPACE)&&!/input|button|textarea/i.test(a.target.nodeName))for(a=a.target;a;a=a.parentNode)if(a.dojoClick)return!0}var a;h(document,"keydown",function(d){f(d)?(a=d.target,d.preventDefault()):
a=null});h(document,"keyup",function(d){f(d)&&d.target==a&&(a=null,h.emit(d.target,"click",{cancelable:!0,bubbles:!0,ctrlKey:d.ctrlKey,shiftKey:d.shiftKey,metaKey:d.metaKey,altKey:d.altKey,_origType:d.type}))});var d=function(a,c){a.dojoClick=!0;return h(a,"click",c)};d.click=d;d.press=function(a,c){var e=h(a,l.press,function(a){("mousedown"!=a.type||k.isLeft(a))&&c(a)}),b=h(a,"keydown",function(a){(a.keyCode===m.ENTER||a.keyCode===m.SPACE)&&c(a)});return{remove:function(){e.remove();b.remove()}}};
d.release=function(a,c){var e=h(a,l.release,function(a){("mouseup"!=a.type||k.isLeft(a))&&c(a)}),b=h(a,"keyup",function(a){(a.keyCode===m.ENTER||a.keyCode===m.SPACE)&&c(a)});return{remove:function(){e.remove();b.remove()}}};d.move=l.move;return d})},"dojo/request":function(){define(["./request/default!"],function(m){return m})},"dijit/hccss":function(){define(["dojo/dom-class","dojo/hccss","dojo/domReady","dojo/_base/window"],function(m,k,h,l){h(function(){k("highcontrast")&&m.add(l.body(),"dijit_a11y")});
return k})},"dijit/_TemplatedMixin":function(){define("dojo/cache dojo/_base/declare dojo/dom-construct dojo/_base/lang dojo/on dojo/sniff dojo/string ./_AttachMixin".split(" "),function(m,k,h,l,f,a,d,g){var c=k("dijit._TemplatedMixin",g,{templateString:null,templatePath:null,_skipNodeCache:!1,searchContainerNode:!0,_stringRepl:function(a){var b=this.declaredClass,c=this;return d.substitute(a,this,function(a,e){"!"==e.charAt(0)&&(a=l.getObject(e.substr(1),!1,c));if("undefined"==typeof a)throw Error(b+
" template:"+e);return null==a?"":"!"==e.charAt(0)?a:this._escapeValue(""+a)},this)},_escapeValue:function(a){return a.replace(/["'<>&]/g,function(a){return{"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;"}[a]})},buildRendering:function(){if(!this._rendered){this.templateString||(this.templateString=m(this.templatePath,{sanitize:!0}));var a=c.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),b;if(l.isString(a)){if(b=h.toDom(this._stringRepl(a),
this.ownerDocument),1!=b.nodeType)throw Error("Invalid template: "+a);}else b=a.cloneNode(!0);this.domNode=b}this.inherited(arguments);this._rendered||this._fillContent(this.srcNodeRef);this._rendered=!0},_fillContent:function(a){var b=this.containerNode;if(a&&b)for(;a.hasChildNodes();)b.appendChild(a.firstChild)}});c._templateCache={};c.getCachedTemplate=function(a,b,f){var g=c._templateCache,k=a,l=g[k];if(l){try{if(!l.ownerDocument||l.ownerDocument==(f||document))return l}catch(m){}h.destroy(l)}a=
d.trim(a);if(b||a.match(/\$\{([^\}]+)\}/g))return g[k]=a;b=h.toDom(a,f);if(1!=b.nodeType)throw Error("Invalid template: "+a);return g[k]=b};a("ie")&&f(window,"unload",function(){var a=c._templateCache,b;for(b in a){var d=a[b];"object"==typeof d&&h.destroy(d);delete a[b]}});return c})},"dijit/selection":function(){define("dojo/_base/array dojo/dom dojo/_base/lang dojo/sniff dojo/_base/window dijit/focus".split(" "),function(m,k,h,l,f,a){var d=function(c){var e=c.document;this.getType=function(){if(e.getSelection){var a=
"text",d;try{d=c.getSelection()}catch(f){}d&&1==d.rangeCount&&(d=d.getRangeAt(0),d.startContainer==d.endContainer&&(1==d.endOffset-d.startOffset&&3!=d.startContainer.nodeType)&&(a="control"));return a}return e.selection.type.toLowerCase()};this.getSelectedText=function(){if(e.getSelection){var a=c.getSelection();return a?a.toString():""}return"control"==this.getType()?null:e.selection.createRange().text};this.getSelectedHtml=function(){if(e.getSelection){var a=c.getSelection();if(a&&a.rangeCount){var d,
f="";for(d=0;d<a.rangeCount;d++){var g=a.getRangeAt(d).cloneContents(),h=e.createElement("div");h.appendChild(g);f+=h.innerHTML}return f}return null}return"control"==this.getType()?null:e.selection.createRange().htmlText};this.getSelectedElement=function(){if("control"==this.getType()){if(e.getSelection){var a=c.getSelection();return a.anchorNode.childNodes[a.anchorOffset]}if((a=e.selection.createRange())&&a.item)return e.selection.createRange().item(0)}return null};this.getParentElement=function(){if("control"==
this.getType()){var a=this.getSelectedElement();if(a)return a.parentNode}else if(e.getSelection){if(a=e.getSelection()){for(a=a.anchorNode;a&&1!=a.nodeType;)a=a.parentNode;return a}}else return a=e.selection.createRange(),a.collapse(!0),a.parentElement();return null};this.hasAncestorElement=function(a){return null!=this.getAncestorElement.apply(this,arguments)};this.getAncestorElement=function(a){var c=this.getSelectedElement()||this.getParentElement();return this.getParentOfType(c,arguments)};this.isTag=
function(a,c){if(a&&a.tagName)for(var e=a.tagName.toLowerCase(),d=0;d<c.length;d++){var f=String(c[d]).toLowerCase();if(e==f)return f}return""};this.getParentOfType=function(a,c){for(;a;){if(this.isTag(a,c).length)return a;a=a.parentNode}return null};this.collapse=function(a){if(e.getSelection){var d=c.getSelection();d.removeAllRanges?a?d.collapseToStart():d.collapseToEnd():d.collapse(a)}else d=e.selection.createRange(),d.collapse(a),d.select()};this.remove=function(){var a=e.selection;e.getSelection?
(a=c.getSelection(),a.deleteFromDocument()):"none"!=a.type.toLowerCase()&&a.clear();return a};this.selectElementChildren=function(a,d){var f;a=k.byId(a);if(e.getSelection){var g=c.getSelection();l("opera")?(f=g.rangeCount?g.getRangeAt(0):e.createRange(),f.setStart(a,0),f.setEnd(a,3==a.nodeType?a.length:a.childNodes.length),g.addRange(f)):g.selectAllChildren(a)}else if(f=a.ownerDocument.body.createTextRange(),f.moveToElementText(a),!d)try{f.select()}catch(h){}};this.selectElement=function(a,c){var d;
a=k.byId(a);if(e.getSelection){var g=e.getSelection();d=e.createRange();g.removeAllRanges&&(l("opera")&&g.getRangeAt(0)&&(d=g.getRangeAt(0)),d.selectNode(a),g.removeAllRanges(),g.addRange(d))}else try{g=a.tagName?a.tagName.toLowerCase():"",d="img"===g||"table"===g?f.body(e).createControlRange():f.body(e).createRange(),d.addElement(a),c||d.select()}catch(h){this.selectElementChildren(a,c)}};this.inSelection=function(a){if(a){var d,f;if(e.getSelection){var g=c.getSelection();g&&0<g.rangeCount&&(f=g.getRangeAt(0));
if(f&&f.compareBoundaryPoints&&e.createRange)try{if(d=e.createRange(),d.setStart(a,0),1===f.compareBoundaryPoints(f.START_TO_END,d))return!0}catch(h){}}else{f=e.selection.createRange();try{d=a.ownerDocument.body.createTextRange(),d.moveToElementText(a)}catch(k){}if(f&&d&&1===f.compareEndPoints("EndToStart",d))return!0}}return!1};this.getBookmark=function(){var b,d,f=e.selection,g=a.curNode;if(e.getSelection){if(f=c.getSelection())if(f.isCollapsed){if(b=g?g.tagName:"")if(b=b.toLowerCase(),"textarea"==
b||"input"==b&&(!g.type||"text"==g.type.toLowerCase()))return f={start:g.selectionStart,end:g.selectionEnd,node:g,pRange:!0},{isCollapsed:f.end<=f.start,mark:f};b={isCollapsed:!0};f.rangeCount&&(b.mark=f.getRangeAt(0).cloneRange())}else d=f.getRangeAt(0),b={isCollapsed:!1,mark:d.cloneRange()}}else if(f){b=g?g.tagName:"";b=b.toLowerCase();if(g&&b&&("button"==b||"textarea"==b||"input"==b)){if(f.type&&"none"==f.type.toLowerCase())return{isCollapsed:!0,mark:null};d=f.createRange();return{isCollapsed:d.text&&
d.text.length?!1:!0,mark:{range:d,pRange:!0}}}b={};try{d=f.createRange(),b.isCollapsed=!("Text"==f.type?d.htmlText.length:d.length)}catch(h){return b.isCollapsed=!0,b}if("CONTROL"==f.type.toUpperCase())if(d.length){b.mark=[];f=0;for(g=d.length;f<g;)b.mark.push(d.item(f++))}else b.isCollapsed=!0,b.mark=null;else b.mark=d.getBookmark()}else console.warn("No idea how to store the current selection for this browser!");return b};this.moveToBookmark=function(a){if(a=a.mark)if(e.getSelection){var d=c.getSelection();
d&&d.removeAllRanges?a.pRange?(d=a.node,d.selectionStart=a.start,d.selectionEnd=a.end):(d.removeAllRanges(),d.addRange(a)):console.warn("No idea how to restore selection for this browser!")}else if(e.selection&&a){var f;a.pRange?f=a.range:h.isArray(a)?(f=e.body.createControlRange(),m.forEach(a,function(a){f.addElement(a)})):(f=e.body.createTextRange(),f.moveToBookmark(a));f.select()}};this.isCollapsed=function(){return this.getBookmark().isCollapsed}},g=new d(window);g.SelectionManager=d;return g})},
"dijit/form/_FormWidget":function(){define("dojo/_base/declare dojo/sniff dojo/_base/kernel dojo/ready ../_Widget ../_CssStateMixin ../_TemplatedMixin ./_FormWidgetMixin".split(" "),function(m,k,h,l,f,a,d,g){k("dijit-legacy-requires")&&l(0,function(){require(["dijit/form/_FormValueWidget"])});return m("dijit.form._FormWidget",[f,d,a,g],{setDisabled:function(a){h.deprecated("setDisabled("+a+") is deprecated. Use set('disabled',"+a+") instead.","","2.0");this.set("disabled",a)},setValue:function(a){h.deprecated("dijit.form._FormWidget:setValue("+
a+") is deprecated.  Use set('value',"+a+") instead.","","2.0");this.set("value",a)},getValue:function(){h.deprecated(this.declaredClass+"::getValue() is deprecated. Use get('value') instead.","","2.0");return this.get("value")},postMixInProperties:function(){this.nameAttrSetting=this.name&&!k("msapp")?'name\x3d"'+this.name.replace(/"/g,"\x26quot;")+'"':"";this.inherited(arguments)}})})},"dijit/_base/focus":function(){define("dojo/_base/array dojo/dom dojo/_base/lang dojo/topic dojo/_base/window ../focus ../selection ../main".split(" "),
function(m,k,h,l,f,a,d,g){a.focus=function(c){if(c){var d="node"in c?c.node:c,b=c.bookmark;c=c.openedForWindow;var h=b?b.isCollapsed:!1;if(d){var k="iframe"==d.tagName.toLowerCase()?d.contentWindow:d;if(k&&k.focus)try{k.focus()}catch(l){}a._onFocusNode(d)}if(b&&f.withGlobal(c||f.global,g.isCollapsed)&&!h){c&&c.focus();try{f.withGlobal(c||f.global,g.moveToBookmark,null,[b])}catch(m){}}}};a.watch("curNode",function(a,d,b){g._curFocus=b;g._prevFocus=d;b&&l.publish("focusNode",b)});a.watch("activeStack",
function(a,d,b){g._activeStack=b});a.on("widget-blur",function(a,d){l.publish("widgetBlur",a,d)});a.on("widget-focus",function(a,d){l.publish("widgetFocus",a,d)});h.mixin(g,{_curFocus:null,_prevFocus:null,isCollapsed:function(){return g.getBookmark().isCollapsed},getBookmark:function(){return(f.global==window?d:new d.SelectionManager(f.global)).getBookmark()},moveToBookmark:function(a){return(f.global==window?d:new d.SelectionManager(f.global)).moveToBookmark(a)},getFocus:function(c,d){var b=!a.curNode||
c&&k.isDescendant(a.curNode,c.domNode)?g._prevFocus:a.curNode;return{node:b,bookmark:b&&b==a.curNode&&f.withGlobal(d||f.global,g.getBookmark),openedForWindow:d}},_activeStack:[],registerIframe:function(c){return a.registerIframe(c)},unregisterIframe:function(a){a&&a.remove()},registerWin:function(c,d){return a.registerWin(c,d)},unregisterWin:function(a){a&&a.remove()}});return g})},"dojo/parser":function(){define("require ./_base/kernel ./_base/lang ./_base/array ./_base/config ./dom ./_base/window ./_base/url ./aspect ./promise/all ./date/stamp ./Deferred ./has ./query ./on ./ready".split(" "),
function(m,k,h,l,f,a,d,g,c,e,b,s,x,v,r,n){function u(a){return eval("("+a+")")}function y(a){var b=a._nameCaseMap,c=a.prototype;if(!b||b._extendCnt<p){var b=a._nameCaseMap={},d;for(d in c)"_"!==d.charAt(0)&&(b[d.toLowerCase()]=d);b._extendCnt=p}return b}function t(a,b){var c=a.join();if(!w[c]){for(var d=[],e=0,f=a.length;e<f;e++){var g=a[e];d[d.length]=w[g]=w[g]||h.getObject(g)||~g.indexOf("/")&&(b?b(g):m(g))}e=d.shift();w[c]=d.length?e.createSubclass?e.createSubclass(d):e.extend.apply(e,d):e}return w[c]}
new Date("X");var p=0;c.after(h,"extend",function(){p++},!0);var w={},D={_clearCache:function(){p++;w={}},_functionFromScript:function(a,b){var c="",d="",e=a.getAttribute(b+"args")||a.getAttribute("args"),f=a.getAttribute("with"),e=(e||"").split(/\s*,\s*/);f&&f.length&&l.forEach(f.split(/\s*,\s*/),function(a){c+="with("+a+"){";d+="}"});return new Function(e,c+a.innerHTML+d)},instantiate:function(a,b,c){b=b||{};c=c||{};var d=(c.scope||k._scopeName)+"Type",e="data-"+(c.scope||k._scopeName)+"-",f=e+
"type",g=e+"mixins",h=[];l.forEach(a,function(a){var c=d in b?b[d]:a.getAttribute(f)||a.getAttribute(d);if(c){var e=a.getAttribute(g),c=e?[c].concat(e.split(/\s*,\s*/)):[c];h.push({node:a,types:c})}});return this._instantiate(h,b,c)},_instantiate:function(a,b,c,d){function f(a){!b._started&&!c.noStart&&l.forEach(a,function(a){"function"===typeof a.startup&&!a._started&&a.startup()});return a}a=l.map(a,function(a){var d=a.ctor||t(a.types,c.contextRequire);if(!d)throw Error("Unable to resolve constructor for: '"+
a.types.join()+"'");return this.construct(d,a.node,b,c,a.scripts,a.inherited)},this);return d?e(a).then(f):f(a)},construct:function(a,d,e,f,m,n){function D(a){w&&h.setObject(w,a);for(B=0;B<L.length;B++)c[L[B].advice||"after"](a,L[B].method,h.hitch(a,L[B].func),!0);for(B=0;B<R.length;B++)R[B].call(a);for(B=0;B<P.length;B++)a.watch(P[B].prop,P[B].func);for(B=0;B<Q.length;B++)r(a,Q[B].event,Q[B].func);return a}var p=a&&a.prototype;f=f||{};var s={};f.defaults&&h.mixin(s,f.defaults);n&&h.mixin(s,n);var t;
x("dom-attributes-explicit")?t=d.attributes:x("dom-attributes-specified-flag")?t=l.filter(d.attributes,function(a){return a.specified}):(n=(/^input$|^img$/i.test(d.nodeName)?d:d.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,"").replace(/^\s*<[a-zA-Z0-9]*\s*/,"").replace(/\s*>.*$/,""),t=l.map(n.split(/\s+/),function(a){var b=a.toLowerCase();return{name:a,value:"LI"==d.nodeName&&"value"==a||"enctype"==b?d.getAttribute(b):d.getAttributeNode(b).value}}));var J=f.scope||k._scopeName;
n="data-"+J+"-";var A={};"dojo"!==J&&(A[n+"props"]="data-dojo-props",A[n+"type"]="data-dojo-type",A[n+"mixins"]="data-dojo-mixins",A[J+"type"]="dojoType",A[n+"id"]="data-dojo-id");for(var B=0,C,J=[],w,N;C=t[B++];){var G=C.name,K=G.toLowerCase();C=C.value;switch(A[K]||K){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;case "data-dojo-props":N=C;break;case "data-dojo-id":case "jsid":w=C;break;case "data-dojo-attach-point":case "dojoattachpoint":s.dojoAttachPoint=C;break;case "data-dojo-attach-event":case "dojoattachevent":s.dojoAttachEvent=
C;break;case "class":s["class"]=d.className;break;case "style":s.style=d.style&&d.style.cssText;break;default:if(G in p||(G=y(a)[K]||G),G in p)switch(typeof p[G]){case "string":s[G]=C;break;case "number":s[G]=C.length?Number(C):NaN;break;case "boolean":s[G]="false"!=C.toLowerCase();break;case "function":""===C||-1!=C.search(/[^\w\.]+/i)?s[G]=new Function(C):s[G]=h.getObject(C,!1)||new Function(C);J.push(G);break;default:K=p[G],s[G]=K&&"length"in K?C?C.split(/\s*,\s*/):[]:K instanceof Date?""==C?new Date(""):
"now"==C?new Date:b.fromISOString(C):K instanceof g?k.baseUrl+C:u(C)}else s[G]=C}}for(t=0;t<J.length;t++)A=J[t].toLowerCase(),d.removeAttribute(A),d[A]=null;if(N)try{N=u.call(f.propsThis,"{"+N+"}"),h.mixin(s,N)}catch(U){throw Error(U.toString()+" in data-dojo-props\x3d'"+N+"'");}h.mixin(s,e);m||(m=a&&(a._noScript||p._noScript)?[]:v("\x3e script[type^\x3d'dojo/']",d));var L=[],R=[],P=[],Q=[];if(m)for(B=0;B<m.length;B++)A=m[B],d.removeChild(A),e=A.getAttribute(n+"event")||A.getAttribute("event"),f=
A.getAttribute(n+"prop"),N=A.getAttribute(n+"method"),J=A.getAttribute(n+"advice"),t=A.getAttribute("type"),A=this._functionFromScript(A,n),e?"dojo/connect"==t?L.push({method:e,func:A}):"dojo/on"==t?Q.push({event:e,func:A}):s[e]=A:"dojo/aspect"==t?L.push({method:N,advice:J,func:A}):"dojo/watch"==t?P.push({prop:f,func:A}):R.push(A);a=(m=a.markupFactory||p.markupFactory)?m(s,d,a):new a(s,d);return a.then?a.then(D):D(a)},scan:function(a,b){function d(a){if(!a.inherited){a.inherited={};var b=a.node,c=
d(a.parent),b={dir:b.getAttribute("dir")||c.dir,lang:b.getAttribute("lang")||c.lang,textDir:b.getAttribute(D)||c.textDir},e;for(e in b)b[e]&&(a.inherited[e]=b[e])}return a.inherited}var c=[],e=[],f={},g=(b.scope||k._scopeName)+"Type",h="data-"+(b.scope||k._scopeName)+"-",n=h+"type",D=h+"textdir",h=h+"mixins",p=a.firstChild,r=b.inherited;if(!r){var u=function(a,b){return a.getAttribute&&a.getAttribute(b)||a.parentNode&&u(a.parentNode,b)},r={dir:u(a,"dir"),lang:u(a,"lang"),textDir:u(a,D)},v;for(v in r)r[v]||
delete r[v]}for(var r={inherited:r},y,w;;)if(p)if(1!=p.nodeType)p=p.nextSibling;else if(y&&"script"==p.nodeName.toLowerCase())(G=p.getAttribute("type"))&&/^dojo\/\w/i.test(G)&&y.push(p),p=p.nextSibling;else if(w)p=p.nextSibling;else{var G=p.getAttribute(n)||p.getAttribute(g);v=p.firstChild;if(!G&&(!v||3==v.nodeType&&!v.nextSibling))p=p.nextSibling;else{w=null;if(G){var K=p.getAttribute(h);y=K?[G].concat(K.split(/\s*,\s*/)):[G];try{w=t(y,b.contextRequire)}catch(U){}w||l.forEach(y,function(a){~a.indexOf("/")&&
!f[a]&&(f[a]=!0,e[e.length]=a)});K=w&&!w.prototype._noScript?[]:null;r={types:y,ctor:w,parent:r,node:p,scripts:K};r.inherited=d(r);c.push(r)}else r={node:p,scripts:y,parent:r};y=K;w=p.stopParser||w&&w.prototype.stopParser&&!b.template;p=v}}else{if(!r||!r.node)break;p=r.node.nextSibling;w=!1;r=r.parent;y=r.scripts}var L=new s;e.length?(x("dojo-debug-messages")&&console.warn("WARNING: Modules being Auto-Required: "+e.join(", ")),(b.contextRequire||m)(e,function(){L.resolve(l.filter(c,function(a){if(!a.ctor)try{a.ctor=
t(a.types,b.contextRequire)}catch(c){}for(var d=a.parent;d&&!d.types;)d=d.parent;var e=a.ctor&&a.ctor.prototype;a.instantiateChildren=!(e&&e.stopParser&&!b.template);a.instantiate=!d||d.instantiate&&d.instantiateChildren;return a.instantiate}))})):L.resolve(c);return L.promise},_require:function(a,b){var d=u("{"+a.innerHTML+"}"),c=[],e=[],f=new s,g=b&&b.contextRequire||m,k;for(k in d)c.push(k),e.push(d[k]);g(e,function(){for(var a=0;a<c.length;a++)h.setObject(c[a],arguments[a]);f.resolve(arguments)});
return f.promise},_scanAmd:function(a,b){var d=new s,c=d.promise;d.resolve(!0);var e=this;v("script[type\x3d'dojo/require']",a).forEach(function(a){c=c.then(function(){return e._require(a,b)});a.parentNode.removeChild(a)});return c},parse:function(b,c){var e;!c&&b&&b.rootNode?(c=b,e=c.rootNode):b&&h.isObject(b)&&!("nodeType"in b)?c=b:e=b;e=e?a.byId(e):d.body();c=c||{};var f=c.template?{template:!0}:{},g=[],k=this,l=this._scanAmd(e,c).then(function(){return k.scan(e,c)}).then(function(a){return k._instantiate(a,
f,c,!0)}).then(function(a){return g=g.concat(a)}).otherwise(function(a){console.error("dojo/parser::parse() error",a);throw a;});h.mixin(g,l);return g}};k.parser=D;f.parseOnLoad&&n(100,D,"parse");return D})},"dijit/layout/_LayoutWidget":function(){define("dojo/_base/lang ../_Widget ../_Container ../_Contained ../Viewport dojo/_base/declare dojo/dom-class dojo/dom-geometry dojo/dom-style".split(" "),function(m,k,h,l,f,a,d,g,c){return a("dijit.layout._LayoutWidget",[k,h,l],{baseClass:"dijitLayoutContainer",
isLayoutContainer:!0,_setTitleAttr:null,buildRendering:function(){this.inherited(arguments);d.add(this.domNode,"dijitContainer")},startup:function(){if(!this._started){this.inherited(arguments);var a=this.getParent&&this.getParent();if(!a||!a.isLayoutContainer)this.resize(),this.own(f.on("resize",m.hitch(this,"resize")))}},resize:function(a,b){var d=this.domNode;a&&g.setMarginBox(d,a);var f=b||{};m.mixin(f,a||{});if(!("h"in f)||!("w"in f))f=m.mixin(g.getMarginBox(d),f);var h=c.getComputedStyle(d),
k=g.getMarginExtents(d,h),l=g.getBorderExtents(d,h),f=this._borderBox={w:f.w-(k.w+l.w),h:f.h-(k.h+l.h)},k=g.getPadExtents(d,h);this._contentBox={l:c.toPixelValue(d,h.paddingLeft),t:c.toPixelValue(d,h.paddingTop),w:f.w-k.w,h:f.h-k.h};this.layout()},layout:function(){},_setupChild:function(a){d.add(a.domNode,this.baseClass+"-child "+(a.baseClass?this.baseClass+"-"+a.baseClass:""))},addChild:function(a,b){this.inherited(arguments);this._started&&this._setupChild(a)},removeChild:function(a){d.remove(a.domNode,
this.baseClass+"-child"+(a.baseClass?" "+this.baseClass+"-"+a.baseClass:""));this.inherited(arguments)}})})},"dijit/_Widget":function(){define("dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/has dojo/_base/kernel dojo/_base/lang dojo/query dojo/ready ./registry ./_WidgetBase ./_OnDijitClickMixin ./_FocusMixin dojo/uacss ./hccss".split(" "),function(m,k,h,l,f,a,d,g,c,e,b,s,x){function v(){}function r(a){return function(b,c,e,f){return b&&"string"==typeof c&&b[c]==v?b.on(c.substring(2).toLowerCase(),
d.hitch(e,f)):a.apply(h,arguments)}}m.around(h,"connect",r);a.connect&&m.around(a,"connect",r);m=l("dijit._Widget",[b,s,x],{onClick:v,onDblClick:v,onKeyDown:v,onKeyPress:v,onKeyUp:v,onMouseDown:v,onMouseMove:v,onMouseOut:v,onMouseOver:v,onMouseLeave:v,onMouseEnter:v,onMouseUp:v,constructor:function(a){this._toConnect={};for(var b in a)this[b]===v&&(this._toConnect[b.replace(/^on/,"").toLowerCase()]=a[b],delete a[b])},postCreate:function(){this.inherited(arguments);for(var a in this._toConnect)this.on(a,
this._toConnect[a]);delete this._toConnect},on:function(a,b){return this[this._onMap(a)]===v?h.connect(this.domNode,a.toLowerCase(),this,b):this.inherited(arguments)},_setFocusedAttr:function(a){this._focused=a;this._set("focused",a)},setAttribute:function(b,c){a.deprecated(this.declaredClass+"::setAttribute(attr, value) is deprecated. Use set() instead.","","2.0");this.set(b,c)},attr:function(a,b){return 2<=arguments.length||"object"===typeof a?this.set.apply(this,arguments):this.get(a)},getDescendants:function(){a.deprecated(this.declaredClass+
"::getDescendants() is deprecated. Use getChildren() instead.","","2.0");return this.containerNode?g("[widgetId]",this.containerNode).map(e.byNode):[]},_onShow:function(){this.onShow()},onShow:function(){},onHide:function(){},onClose:function(){return!0}});f("dijit-legacy-requires")&&c(0,function(){require(["dijit/_base"])});return m})},"dijit/_FocusMixin":function(){define(["./focus","./_WidgetBase","dojo/_base/declare","dojo/_base/lang"],function(m,k,h,l){l.extend(k,{focused:!1,onFocus:function(){},
onBlur:function(){},_onFocus:function(){this.onFocus()},_onBlur:function(){this.onBlur()}});return h("dijit._FocusMixin",null,{_focusManager:m})})},"dijit/focus":function(){define("dojo/aspect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/Evented dojo/_base/lang dojo/on dojo/domReady dojo/sniff dojo/Stateful dojo/_base/window dojo/window ./a11y ./registry ./main".split(" "),function(m,k,h,l,f,a,d,g,c,e,b,s,x,v,r,n,u){var y,t,p=new (k([s,d],{curNode:null,activeStack:[],
constructor:function(){var b=g.hitch(this,function(a){h.isDescendant(this.curNode,a)&&this.set("curNode",null);h.isDescendant(this.prevNode,a)&&this.set("prevNode",null)});m.before(a,"empty",b);m.before(a,"destroy",b)},registerIframe:function(a){return this.registerWin(a.contentWindow,a)},registerWin:function(a,d){var e=this,f=a.document&&a.document.body;if(f){var g=b("pointer-events")?"pointerdown":b("MSPointer")?"MSPointerDown":b("touch-events")?"mousedown, touchstart":"mousedown",h=c(a.document,
g,function(a){if(!a||!(a.target&&null==a.target.parentNode))e._onTouchNode(d||a.target,"mouse")}),k=c(f,"focusin",function(a){if(a.target.tagName){var b=a.target.tagName.toLowerCase();"#document"==b||"body"==b||(r.isFocusable(a.target)?e._onFocusNode(d||a.target):e._onTouchNode(d||a.target))}}),l=c(f,"focusout",function(a){e._onBlurNode(d||a.target)});return{remove:function(){h.remove();k.remove();l.remove();f=h=k=l=null}}}},_onBlurNode:function(a){a=(new Date).getTime();a<y+100||(this._clearFocusTimer&&
clearTimeout(this._clearFocusTimer),this._clearFocusTimer=setTimeout(g.hitch(this,function(){this.set("prevNode",this.curNode);this.set("curNode",null)}),0),this._clearActiveWidgetsTimer&&clearTimeout(this._clearActiveWidgetsTimer),a<t+100||(this._clearActiveWidgetsTimer=setTimeout(g.hitch(this,function(){delete this._clearActiveWidgetsTimer;this._setStack([])}),0)))},_onTouchNode:function(a,b){t=(new Date).getTime();this._clearActiveWidgetsTimer&&(clearTimeout(this._clearActiveWidgetsTimer),delete this._clearActiveWidgetsTimer);
f.contains(a,"dijitPopup")&&(a=a.firstChild);var d=[];try{for(;a;){var c=l.get(a,"dijitPopupParent");if(c)a=n.byId(c).domNode;else if(a.tagName&&"body"==a.tagName.toLowerCase()){if(a===x.body())break;a=v.get(a.ownerDocument).frameElement}else{var e=a.getAttribute&&a.getAttribute("widgetId"),g=e&&n.byId(e);g&&!("mouse"==b&&g.get("disabled"))&&d.unshift(e);a=a.parentNode}}}catch(h){}this._setStack(d,b)},_onFocusNode:function(a){a&&9!=a.nodeType&&(y=(new Date).getTime(),this._clearFocusTimer&&(clearTimeout(this._clearFocusTimer),
delete this._clearFocusTimer),this._onTouchNode(a),a!=this.curNode&&(this.set("prevNode",this.curNode),this.set("curNode",a)))},_setStack:function(a,b){var d=this.activeStack,c=d.length-1,e=a.length-1;if(a[e]!=d[c]){this.set("activeStack",a);var f;for(f=c;0<=f&&d[f]!=a[f];f--)if(c=n.byId(d[f]))c._hasBeenBlurred=!0,c.set("focused",!1),c._focusManager==this&&c._onBlur(b),this.emit("widget-blur",c,b);for(f++;f<=e;f++)if(c=n.byId(a[f]))c.set("focused",!0),c._focusManager==this&&c._onFocus(b),this.emit("widget-focus",
c,b)}},focus:function(a){if(a)try{a.focus()}catch(b){}}}));e(function(){var a=p.registerWin(v.get(document));b("ie")&&c(window,"unload",function(){a&&(a.remove(),a=null)})});u.focus=function(a){p.focus(a)};for(var w in p)/^_/.test(w)||(u.focus[w]="function"==typeof p[w]?g.hitch(p,w):p[w]);p.watch(function(a,b,c){u.focus[a]=c});return p})},"dijit/_Contained":function(){define(["dojo/_base/declare","./registry"],function(m,k){return m("dijit._Contained",null,{_getSibling:function(h){var l=this.domNode;
do l=l[h+"Sibling"];while(l&&1!=l.nodeType);return l&&k.byNode(l)},getPreviousSibling:function(){return this._getSibling("previous")},getNextSibling:function(){return this._getSibling("next")},getIndexInParent:function(){var h=this.getParent();return!h||!h.getIndexOfChild?-1:h.getIndexOfChild(this)}})})},"dijit/_base/scroll":function(){define(["dojo/window","../main"],function(m,k){k.scrollIntoView=function(h,k){m.scrollIntoView(h,k)}})},"dijit/main":function(){define(["dojo/_base/kernel"],function(m){return m.dijit})},
"dijit/Destroyable":function(){define(["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(m,k,h){return h("dijit.Destroyable",null,{destroy:function(h){this._destroyed=!0},own:function(){var h=["destroyRecursive","destroy","remove"];m.forEach(arguments,function(f){function a(){g.remove();m.forEach(c,function(a){a.remove()})}var d,g=k.before(this,"destroy",function(a){f[d](a)}),c=[];f.then?(d="cancel",f.then(a,a)):m.forEach(h,function(e){"function"===typeof f[e]&&(d||(d=e),c.push(k.after(f,
e,a,!0)))})},this);return arguments}})})},"dojo/cache":function(){define(["./_base/kernel","./text"],function(m){return m.cache})},"dijit/_base/window":function(){define(["dojo/window","../main"],function(m,k){k.getDocumentWindow=function(h){return m.get(h)}})},"dijit/_base/typematic":function(){define(["../typematic"],function(){})},"dijit/_base/popup":function(){define(["dojo/dom-class","dojo/_base/window","../popup","../BackgroundIframe"],function(m,k,h){var l=h._createWrapper;h._createWrapper=
function(a){a.declaredClass||(a={_popupWrapper:a.parentNode&&m.contains(a.parentNode,"dijitPopup")?a.parentNode:null,domNode:a,destroy:function(){},ownerDocument:a.ownerDocument,ownerDocumentBody:k.body(a.ownerDocument)});return l.call(this,a)};var f=h.open;h.open=function(a){if(a.orient&&"string"!=typeof a.orient&&!("length"in a.orient)){var d=[],g;for(g in a.orient)d.push({aroundCorner:g,corner:a.orient[g]});a.orient=d}return f.call(this,a)};return h})},"dijit/_Container":function(){define(["dojo/_base/array",
"dojo/_base/declare","dojo/dom-construct","dojo/_base/kernel"],function(m,k,h,l){return k("dijit._Container",null,{buildRendering:function(){this.inherited(arguments);this.containerNode||(this.containerNode=this.domNode)},addChild:function(f,a){var d=this.containerNode;if(0<a){if(d=d.firstChild)for(;d&&0<a;)1==d.nodeType&&a--,d=d.nextSibling;d?a="before":(d=this.containerNode,a="last")}h.place(f.domNode,d,a);this._started&&!f._started&&f.startup()},removeChild:function(f){"number"==typeof f&&(f=this.getChildren()[f]);
f&&(f=f.domNode)&&f.parentNode&&f.parentNode.removeChild(f)},hasChildren:function(){return 0<this.getChildren().length},_getSiblingOfChild:function(f,a){l.deprecated(this.declaredClass+"::_getSiblingOfChild() is deprecated. Use _KeyNavMixin::_getNext() instead.","","2.0");var d=this.getChildren(),g=m.indexOf(d,f);return d[g+a]},getIndexOfChild:function(f){return m.indexOf(this.getChildren(),f)}})})}}});
define("dijit/dijit","./main ./_base dojo/parser ./_Widget ./_TemplatedMixin ./_Container ./layout/_LayoutWidget ./form/_FormWidget ./form/_FormValueWidget".split(" "),function(m){return m});
//# sourceMappingURL=dijit.js.map