/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: dhcpd.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _DHCPD_H_
#define _DHCPD_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef dhcpd__ns
#define dhcpd__ns 1946994318
#define dhcpd__ns_id "http://tail-f.com/ns/example/dhcpd"
#define dhcpd__ns_uri "http://tail-f.com/ns/example/dhcpd"
#endif

#define dhcpd_vector 1419181298
#define dhcpd_defaultLeaseTime 118129111
#define dhcpd_lst_index1 855541752
#define dhcpd_listcontent2 2070552292
#define dhcpd_name 1998270519
#define dhcpd_a 1589197455
#define dhcpd_range 28853268
#define dhcpd_SubNets 1256845656
#define dhcpd_subNet 1913521436
#define dhcpd_dhcp 990408299
#define dhcpd_net 872020178
#define dhcpd_mask 1167181041
#define dhcpd_kern 0
#define dhcpd_local7 2
#define dhcpd_SharedNetworks 1803341112
#define dhcpd_routers 1226429584
#define dhcpd_mail 1
#define dhcpd_maxLeaseTime 636170887
#define dhcpd_sharedNetwork 1046159334
#define dhcpd_hiAddr 1434563521
#define dhcpd_b 554582006
#define dhcpd_listcontent3 1393747164
#define dhcpd_lst_index2 1448437492
#define dhcpd_logFacility 255866064
#define dhcpd_listcontent1 1224576905
#define dhcpd_lowAddr 1530146337
#define dhcpd_dynamicBootP 1183305956
#define dhcpd_try_list 77747704

#ifdef __cplusplus
}
#endif

#endif
