//>>built
define("dojox/charting/plot2d/Columns","dojo/_base/lang dojo/_base/array dojo/_base/declare dojo/has ./CartesianBase ./_PlotEvents ./common dojox/lang/functional dojox/lang/functional/reversed dojox/lang/utils dojox/gfx/fx dojox/gfx/gradutils".split(" "),function(s,z,B,C,D,E,t,F,G,u,H,I){function v(){return!1}var J=G.lambda("item.purgeGroup()");return B("dojox.charting.plot2d.Columns",[D,E],{defaultParams:{gap:0,animate:null,enableCache:!1},optionalParams:{minBarSize:1,maxBarSize:1,minWidth:0,stroke:{},
outline:{},shadow:{},fill:{},filter:{},styleFunc:null,font:"",fontColor:""},constructor:function(a,b){this.opt=s.clone(s.mixin(this.opt,this.defaultParams));u.updateWithObject(this.opt,b);u.updateWithPattern(this.opt,b,this.optionalParams);this.animate=this.opt.animate},getSeriesStats:function(){var a=t.collectSimpleStats(this.series,s.hitch(this,"isNullValue"));a.hmin-=0.5;a.hmax+=0.5;return a},createRect:function(a,b,e){var c;this.opt.enableCache&&0<a._rectFreePool.length?(c=a._rectFreePool.pop(),
c.setShape(e),b.add(c)):c=b.createRect(e);this.opt.enableCache&&a._rectUsePool.push(c);return c},render:function(a,b){if(this.zoom&&!this.isDataDirty())return this.performZoom(a,b);this.resetEvents();this.dirty=this.isDirty();var e;this.dirty&&(z.forEach(this.series,J),this._eventSeries={},this.cleanGroup(),e=this.getGroup(),F.forEachRev(this.series,function(a){a.cleanGroup(e)}));for(var c=this.chart.theme,l=this._hScaler.scaler.getTransformerFromModel(this._hScaler),d=this._vScaler.scaler.getTransformerFromModel(this._vScaler),
h=Math.max(this._vScaler.bounds.lower,this._vAxis?this._vAxis.naturalBaseline:0),h=d(h),n=this.events(),p=this.getBarProperties(),A=this.extractValues(this._hScaler),A=this.rearrangeValues(A,d,h),d=0;d<this.series.length;d++){var f=this.series[d];if(!this.dirty&&!f.dirty)c.skip(),this._reconnectEvents(f.name);else{f.cleanGroup();this.opt.enableCache&&(f._rectFreePool=(f._rectFreePool?f._rectFreePool:[]).concat(f._rectUsePool?f._rectUsePool:[]),f._rectUsePool=[]);var t=c.next("column",[this.opt,f]),
u=Array(f.data.length);e=f.group;for(var y=z.some(f.data,function(a){return"number"==typeof a||a&&!a.hasOwnProperty("x")}),r=y?Math.max(0,Math.floor(this._hScaler.bounds.from-1)):0,y=y?Math.min(f.data.length,Math.ceil(this._hScaler.bounds.to)):f.data.length;r<y;++r){var g=f.data[r];if(!this.isNullValue(g)){var w="number"==typeof g||isNaN(g.x)?r:g.x-1,v="number"==typeof g?g:g.y,x=A[d][r],q;if(this.opt.styleFunc||"number"!=typeof g){var k="number"!=typeof g?[g]:[];this.opt.styleFunc&&k.push(this.opt.styleFunc(g));
g=c.addMixin(t,"column",k,!0)}else g=c.post(t,"column");if(x&&1<=p.width){k={x:b.l+l(w+0.5)+p.gap+p.thickness*d,y:a.height-b.b-h-Math.max(x,0),width:p.width,height:Math.abs(x)};g.series.shadow&&(q=s.clone(k),q.x+=g.series.shadow.dx,q.y+=g.series.shadow.dy,q=this.createRect(f,e,q).setFill(g.series.shadow.color).setStroke(g.series.shadow),this.animate&&this._animateColumn(q,a.height-b.b+h,Math.abs(x)));var m=g.series.fill;0>v&&m&&("linear"===m.type&&m.colors&&2===m.colors.length)&&(m=I.reverse(m));
m=this._plotFill(m,a,b);m=this._shapeFill(m,k);k=this.createRect(f,e,k).setFill(m).setStroke(g.series.stroke);k.setFilter&&g.series.filter&&k.setFilter(g.series.filter);f.dyn.fill=k.getFill();f.dyn.stroke=k.getStroke();n&&(w={element:"column",index:r,run:f,shape:k,shadow:q,x:w+0.5,y:v},this._connectEvents(w),u[r]=w);this.animate&&this._animateColumn(k,a.height-b.b-h,Math.abs(x))}}}this._eventSeries[f.name]=u;f.dirty=!1}}this.dirty=!1;C("dojo-bidi")&&this._checkOrientation(this.group,a,b);return this},
extractValues:function(a){for(var b=[],e=this.series.length-1;0<=e;--e){var c=this.series[e];if(this.dirty||c.dirty){var l=z.some(c.data,function(a){return"number"==typeof a||a&&!a.hasOwnProperty("x")}),d=l?Math.max(0,Math.floor(a.bounds.from-1)):0,l=l?Math.min(c.data.length,Math.ceil(a.bounds.to)):c.data.length,h=b[e]=[];h.min=d;for(h.max=l;d<l;++d){var n=c.data[d];h[d]=this.isNullValue(n)?0:"number"==typeof n?n:n.y}}}return b},rearrangeValues:function(a,b,e){for(var c=0,l=a.length;c<l;++c){var d=
a[c];if(d)for(var h=d.min,n=d.max;h<n;++h){var p=d[h];d[h]=this.isNullValue(p)?0:b(p)-e}}if(this.opt.minWidth){b=this.opt.minWidth;c=0;for(l=a.length;c<l;++c)if(d=a[c]){h=d.min;for(n=d.max;h<n;++h)p=d[h],0<p&&p<b&&(d[h]=b)}}return a},isNullValue:function(a){if(null===a||"undefined"==typeof a)return!0;var b=this._hAxis?this._hAxis.isNullValue:v,e=this._vAxis?this._vAxis.isNullValue:v;return"number"==typeof a?e(0.5)||b(a):e(isNaN(a.x)?0.5:a.x+0.5)||null===a.y||b(a.y)},getBarProperties:function(){var a=
t.calculateBarSize(this._hScaler.bounds.scale,this.opt);return{gap:a.gap,width:a.size,thickness:0}},_animateColumn:function(a,b,e){0==e&&(e=1);H.animateTransform(s.delegate({shape:a,duration:1200,transform:[{name:"translate",start:[0,b-b/e],end:[0,0]},{name:"scale",start:[1,1/e],end:[1,1]},{name:"original"}]},this.animate)).play()}})});
//# sourceMappingURL=Columns.js.map