//>>built
define("dojox/charting/plot2d/Default","dojo/_base/lang dojo/_base/declare dojo/_base/array dojo/has ./CartesianBase ./_PlotEvents ./common dojox/lang/functional dojox/lang/functional/reversed dojox/lang/utils dojox/gfx/fx".split(" "),function(s,F,n,L,M,N,x,O,P,y,Q){var R=P.lambda("item.purgeGroup()");return F("dojox.charting.plot2d.Default",[M,N],{defaultParams:{lines:!0,areas:!1,markers:!1,tension:"",animate:!1,enableCache:!1,interpolate:!1},optionalParams:{stroke:{},outline:{},shadow:{},fill:{},
filter:{},styleFunc:null,font:"",fontColor:"",marker:"",markerStroke:{},markerOutline:{},markerShadow:{},markerFill:{},markerFont:"",markerFontColor:"",zeroLine:0},constructor:function(k,b){this.opt=s.clone(s.mixin(this.opt,this.defaultParams));y.updateWithObject(this.opt,b);y.updateWithPattern(this.opt,b,this.optionalParams);this.animate=this.opt.animate},createPath:function(k,b,c){var f;this.opt.enableCache&&0<k._pathFreePool.length?(f=k._pathFreePool.pop(),f.setShape(c),b.add(f)):f=b.createPath(c);
this.opt.enableCache&&k._pathUsePool.push(f);return f},buildSegments:function(k,b){for(var c=this.series[k],f=b?Math.max(0,Math.floor(this._hScaler.bounds.from-1)):0,n=b?Math.min(c.data.length,Math.ceil(this._hScaler.bounds.to)):c.data.length,g=null,s=[];f<n;f++)if(this.isNullValue(c.data[f])){if(!this.opt.interpolate||b)g=null}else g||(g=[],s.push({index:f,rseg:g})),g.push(b&&c.data[f].hasOwnProperty("y")?c.data[f].y:c.data[f]);return s},render:function(k,b){if(this.zoom&&!this.isDataDirty())return this.performZoom(k,
b);this.resetEvents();this.dirty=this.isDirty();var c;this.dirty&&(n.forEach(this.series,R),this._eventSeries={},this.cleanGroup(),this.getGroup().setTransform(null),c=this.getGroup(),O.forEachRev(this.series,function(e){e.cleanGroup(c)}));for(var f=this.chart.theme,r,g,y=this.events(),z=0;z<this.series.length;z++){var a=this.series[z];if(!this.dirty&&!a.dirty)f.skip(),this._reconnectEvents(a.name);else if(a.cleanGroup(),this.opt.enableCache&&(a._pathFreePool=(a._pathFreePool?a._pathFreePool:[]).concat(a._pathUsePool?
a._pathUsePool:[]),a._pathUsePool=[]),a.data.length){var h=f.next(this.opt.areas?"area":"line",[this.opt,a],!0),d,G=this._hScaler.scaler.getTransformerFromModel(this._hScaler),A=this._vScaler.scaler.getTransformerFromModel(this._vScaler),F=this._eventSeries[a.name]=Array(a.data.length);c=a.group;for(var B=n.some(a.data,function(e){return"number"==typeof e||e&&!e.hasOwnProperty("x")}),C=this.buildSegments(z,B),u=0;u<C.length;u++){var m=C[u];d=B?n.map(m.rseg,function(e,a){return{x:G(a+m.index+1)+b.l,
y:k.height-b.b-A(e),data:e}},this):n.map(m.rseg,function(e){return{x:G(e.x)+b.l,y:k.height-b.b-A(e.y),data:e}},this);if(B&&this.opt.interpolate)for(;u<C.length;)u++,(m=C[u])&&(d=d.concat(n.map(m.rseg,function(e,a){return{x:G(a+m.index+1)+b.l,y:k.height-b.b-A(e),data:e}},this)));var p=this.opt.tension?x.curve(d,this.opt.tension):"";if(this.opt.areas&&1<d.length){var v=this._plotFill(h.series.fill,k,b),q=s.clone(d),w=k.height-b.b;isNaN(this.opt.zeroLine)||(w=Math.max(b.t,Math.min(k.height-b.b-A(this.opt.zeroLine),
w)));this.opt.tension?a.dyn.fill=c.createPath(p+" "+("L"+q[q.length-1].x+","+w+" L"+q[0].x+","+w+" L"+q[0].x+","+q[0].y)).setFill(v).getFill():(q.push({x:d[d.length-1].x,y:w}),q.push({x:d[0].x,y:w}),q.push(d[0]),a.dyn.fill=c.createPolyline(q).setFill(v).getFill())}if(this.opt.lines||this.opt.markers)r=h.series.stroke,h.series.outline&&(g=a.dyn.outline=x.makeStroke(h.series.outline),g.width=2*g.width+(r&&r.width||0));this.opt.markers&&(a.dyn.marker=h.symbol);var D=null,H=null,I=null;if(r&&h.series.shadow&&
1<d.length){var t=h.series.shadow,v=n.map(d,function(a){return{x:a.x+t.dx,y:a.y+t.dy}});this.opt.lines&&(a.dyn.shadow=this.opt.tension?c.createPath(x.curve(v,this.opt.tension)).setStroke(t).getStroke():c.createPolyline(v).setStroke(t).getStroke());this.opt.markers&&h.marker.shadow&&(t=h.marker.shadow,I=n.map(v,function(e){return this.createPath(a,c,"M"+e.x+" "+e.y+" "+h.symbol).setStroke(t).setFill(t.color)},this))}if(this.opt.lines&&1<d.length){var E;g&&(a.dyn.outline=this.opt.tension?c.createPath(p).setStroke(g).getStroke():
c.createPolyline(d).setStroke(g).getStroke());a.dyn.stroke=this.opt.tension?(E=c.createPath(p)).setStroke(r).getStroke():(E=c.createPolyline(d)).setStroke(r).getStroke();E.setFilter&&h.series.filter&&E.setFilter(h.series.filter)}p=null;if(this.opt.markers){var l=h,D=Array(d.length),H=Array(d.length);g=null;l.marker.outline&&(g=x.makeStroke(l.marker.outline),g.width=2*g.width+(l.marker.stroke?l.marker.stroke.width:0));n.forEach(d,function(e,b){if(this.opt.styleFunc||"number"!=typeof e.data){var d=
"number"!=typeof e.data?[e.data]:[];this.opt.styleFunc&&d.push(this.opt.styleFunc(e.data));l=f.addMixin(h,"marker",d,!0)}else l=f.post(h,"marker");d="M"+e.x+" "+e.y+" "+l.symbol;g&&(H[b]=this.createPath(a,c,d).setStroke(g));D[b]=this.createPath(a,c,d).setStroke(l.marker.stroke).setFill(l.marker.fill)},this);a.dyn.markerFill=l.marker.fill;a.dyn.markerStroke=l.marker.stroke;!p&&this.opt.labels&&(p=D[0].getBoundingBox());y?n.forEach(D,function(e,b){var c={element:"marker",index:b+m.index,run:a,shape:e,
outline:H[b]||null,shadow:I&&I[b]||null,cx:d[b].x,cy:d[b].y};B?(c.x=b+m.index+1,c.y=a.data[b+m.index]):(c.x=m.rseg[b].x,c.y=a.data[b+m.index].y);this._connectEvents(c);F[b+m.index]=c},this):delete this._eventSeries[a.name]}if(this.opt.labels){var J=p?p.width:2,K=p?p.height:2;n.forEach(d,function(a,b){if(this.opt.styleFunc||"number"!=typeof a.data){var d="number"!=typeof a.data?[a.data]:[];this.opt.styleFunc&&d.push(this.opt.styleFunc(a.data));l=f.addMixin(h,"marker",d,!0)}else l=f.post(h,"marker");
this.createLabel(c,m.rseg[b],{x:a.x-J/2,y:a.y-K/2,width:J,height:K},l)},this)}}a.dirty=!1}else a.dirty=!1,f.skip()}L("dojo-bidi")&&this._checkOrientation(this.group,k,b);this.animate&&(r=this.getGroup(),Q.animateTransform(s.delegate({shape:r,duration:1200,transform:[{name:"translate",start:[0,k.height-b.b],end:[0,0]},{name:"scale",start:[1,0],end:[1,1]},{name:"original"}]},this.animate)).play());this.dirty=!1;return this}})});
//# sourceMappingURL=Default.js.map